/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.everwin.sx.client.model.ServletRequest;
import fr.everwin.sx.client.model.ServletResponse;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AsyncContext
 */
public class AsyncContextTest {
    private final AsyncContext model = new AsyncContext();

    /**
     * Model tests for AsyncContext
     */
    @Test
    public void testAsyncContext() {
        // TODO: test AsyncContext
    }

    /**
     * Test the property 'response'
     */
    @Test
    public void responseTest() {
        // TODO: test response
    }

    /**
     * Test the property 'request'
     */
    @Test
    public void requestTest() {
        // TODO: test request
    }

    /**
     * Test the property 'timeout'
     */
    @Test
    public void timeoutTest() {
        // TODO: test timeout
    }

}
