/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for BookCodeList
 */
public class BookCodeListTest {
    private final BookCodeList model = new BookCodeList();

    /**
     * Model tests for BookCodeList
     */
    @Test
    public void testBookCodeList() {
        // TODO: test BookCodeList
    }

    /**
     * Test the property 'bookCodes'
     */
    @Test
    public void bookCodesTest() {
        // TODO: test bookCodes
    }

}
