/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.everwin.sx.client.model.CompanyDataLink;
import fr.everwin.sx.client.model.CountryDataLink;
import fr.everwin.sx.client.model.CurrencyDataLink;
import fr.everwin.sx.client.model.DataLink;
import fr.everwin.sx.client.model.EmployeeDataLink;
import fr.everwin.sx.client.model.EntityDataLink;
import fr.everwin.sx.client.model.GeographicalAreaDataLink;
import fr.everwin.sx.client.model.NaceDataLink;
import fr.everwin.sx.client.model.SpecificData;
import fr.everwin.sx.client.model.StatusDataLink;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonFormat;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Company
 */
public class CompanyTest {
    private final Company model = new Company();

    /**
     * Model tests for Company
     */
    @Test
    public void testCompany() {
        // TODO: test Company
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'group'
     */
    @Test
    public void groupTest() {
        // TODO: test group
    }

    /**
     * Test the property 'providedby'
     */
    @Test
    public void providedbyTest() {
        // TODO: test providedby
    }

    /**
     * Test the property 'entity'
     */
    @Test
    public void entityTest() {
        // TODO: test entity
    }

    /**
     * Test the property 'accountManager'
     */
    @Test
    public void accountManagerTest() {
        // TODO: test accountManager
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'legalStatus'
     */
    @Test
    public void legalStatusTest() {
        // TODO: test legalStatus
    }

    /**
     * Test the property 'visibility'
     */
    @Test
    public void visibilityTest() {
        // TODO: test visibility
    }

    /**
     * Test the property 'visibilityDate'
     */
    @Test
    public void visibilityDateTest() {
        // TODO: test visibilityDate
    }

    /**
     * Test the property 'identifierNumber'
     */
    @Test
    public void identifierNumberTest() {
        // TODO: test identifierNumber
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'fax'
     */
    @Test
    public void faxTest() {
        // TODO: test fax
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'address2'
     */
    @Test
    public void address2Test() {
        // TODO: test address2
    }

    /**
     * Test the property 'address3'
     */
    @Test
    public void address3Test() {
        // TODO: test address3
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'website'
     */
    @Test
    public void websiteTest() {
        // TODO: test website
    }

    /**
     * Test the property 'defaultAccount'
     */
    @Test
    public void defaultAccountTest() {
        // TODO: test defaultAccount
    }

    /**
     * Test the property 'ape'
     */
    @Test
    public void apeTest() {
        // TODO: test ape
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'segment'
     */
    @Test
    public void segmentTest() {
        // TODO: test segment
    }

    /**
     * Test the property 'openSegment'
     */
    @Test
    public void openSegmentTest() {
        // TODO: test openSegment
    }

    /**
     * Test the property 'turnoverSize'
     */
    @Test
    public void turnoverSizeTest() {
        // TODO: test turnoverSize
    }

    /**
     * Test the property 'turnover'
     */
    @Test
    public void turnoverTest() {
        // TODO: test turnover
    }

    /**
     * Test the property 'numberOfEmployeesSize'
     */
    @Test
    public void numberOfEmployeesSizeTest() {
        // TODO: test numberOfEmployeesSize
    }

    /**
     * Test the property 'numberOfEmployees'
     */
    @Test
    public void numberOfEmployeesTest() {
        // TODO: test numberOfEmployees
    }

    /**
     * Test the property 'numberOfSites'
     */
    @Test
    public void numberOfSitesTest() {
        // TODO: test numberOfSites
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'isProvider'
     */
    @Test
    public void isProviderTest() {
        // TODO: test isProvider
    }

    /**
     * Test the property 'spanco'
     */
    @Test
    public void spancoTest() {
        // TODO: test spanco
    }

    /**
     * Test the property 'updatedOnTime'
     */
    @Test
    public void updatedOnTimeTest() {
        // TODO: test updatedOnTime
    }

    /**
     * Test the property 'createdOnTime'
     */
    @Test
    public void createdOnTimeTest() {
        // TODO: test createdOnTime
    }

    /**
     * Test the property 'updatedBy'
     */
    @Test
    public void updatedByTest() {
        // TODO: test updatedBy
    }

    /**
     * Test the property 'offers'
     */
    @Test
    public void offersTest() {
        // TODO: test offers
    }

    /**
     * Test the property 'acceptEmailing'
     */
    @Test
    public void acceptEmailingTest() {
        // TODO: test acceptEmailing
    }

    /**
     * Test the property 'companyRegistrationNumber'
     */
    @Test
    public void companyRegistrationNumberTest() {
        // TODO: test companyRegistrationNumber
    }

    /**
     * Test the property 'logo'
     */
    @Test
    public void logoTest() {
        // TODO: test logo
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'extraData'
     */
    @Test
    public void extraDataTest() {
        // TODO: test extraData
    }

}
