/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for EntityList
 */
public class EntityListTest {
    private final EntityList model = new EntityList();

    /**
     * Model tests for EntityList
     */
    @Test
    public void testEntityList() {
        // TODO: test EntityList
    }

    /**
     * Test the property 'entities'
     */
    @Test
    public void entitiesTest() {
        // TODO: test entities
    }

}
