/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectPhaseCategoryDataLink
 */
public class ProjectPhaseCategoryDataLinkTest {
    private final ProjectPhaseCategoryDataLink model = new ProjectPhaseCategoryDataLink();

    /**
     * Model tests for ProjectPhaseCategoryDataLink
     */
    @Test
    public void testProjectPhaseCategoryDataLink() {
        // TODO: test ProjectPhaseCategoryDataLink
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

}
