/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.everwin.sx.client.model.DataLink;
import fr.everwin.sx.client.model.PurchaseExpenseInvoicingDetail;
import fr.everwin.sx.client.model.TimeInvoicingDetail;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectLineInvoicing
 */
public class ProjectLineInvoicingTest {
    private final ProjectLineInvoicing model = new ProjectLineInvoicing();

    /**
     * Model tests for ProjectLineInvoicing
     */
    @Test
    public void testProjectLineInvoicing() {
        // TODO: test ProjectLineInvoicing
    }

    /**
     * Test the property 'projectLine'
     */
    @Test
    public void projectLineTest() {
        // TODO: test projectLine
    }

    /**
     * Test the property 'toInvoiceUnit'
     */
    @Test
    public void toInvoiceUnitTest() {
        // TODO: test toInvoiceUnit
    }

    /**
     * Test the property 'invoiced'
     */
    @Test
    public void invoicedTest() {
        // TODO: test invoiced
    }

    /**
     * Test the property 'proforma'
     */
    @Test
    public void proformaTest() {
        // TODO: test proforma
    }

    /**
     * Test the property 'preinvoiced'
     */
    @Test
    public void preinvoicedTest() {
        // TODO: test preinvoiced
    }

    /**
     * Test the property 'quantityToInvoice'
     */
    @Test
    public void quantityToInvoiceTest() {
        // TODO: test quantityToInvoice
    }

    /**
     * Test the property 'bonusMalusTotal'
     */
    @Test
    public void bonusMalusTotalTest() {
        // TODO: test bonusMalusTotal
    }

    /**
     * Test the property 'totalToInvoice'
     */
    @Test
    public void totalToInvoiceTest() {
        // TODO: test totalToInvoice
    }

    /**
     * Test the property 'purchaseExpenseToInvoiceDetails'
     */
    @Test
    public void purchaseExpenseToInvoiceDetailsTest() {
        // TODO: test purchaseExpenseToInvoiceDetails
    }

    /**
     * Test the property 'bonusMalusQuantity'
     */
    @Test
    public void bonusMalusQuantityTest() {
        // TODO: test bonusMalusQuantity
    }

    /**
     * Test the property 'outstandingQuantity'
     */
    @Test
    public void outstandingQuantityTest() {
        // TODO: test outstandingQuantity
    }

    /**
     * Test the property 'outstandingTotal'
     */
    @Test
    public void outstandingTotalTest() {
        // TODO: test outstandingTotal
    }

    /**
     * Test the property 'timeToInvoiceDetails'
     */
    @Test
    public void timeToInvoiceDetailsTest() {
        // TODO: test timeToInvoiceDetails
    }

}
