/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectionRequest
 */
public class ProjectionRequestTest {
    private final ProjectionRequest model = new ProjectionRequest();

    /**
     * Model tests for ProjectionRequest
     */
    @Test
    public void testProjectionRequest() {
        // TODO: test ProjectionRequest
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

}
