/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectState
 */
public class ProjectStateTest {
    private final ProjectState model = new ProjectState();

    /**
     * Model tests for ProjectState
     */
    @Test
    public void testProjectState() {
        // TODO: test ProjectState
    }

    /**
     * Test the property 'revenue'
     */
    @Test
    public void revenueTest() {
        // TODO: test revenue
    }

    /**
     * Test the property 'expenditure'
     */
    @Test
    public void expenditureTest() {
        // TODO: test expenditure
    }

}
