/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for PurchaseExpenseInvoicingDetail
 */
public class PurchaseExpenseInvoicingDetailTest {
    private final PurchaseExpenseInvoicingDetail model = new PurchaseExpenseInvoicingDetail();

    /**
     * Model tests for PurchaseExpenseInvoicingDetail
     */
    @Test
    public void testPurchaseExpenseInvoicingDetail() {
        // TODO: test PurchaseExpenseInvoicingDetail
    }

    /**
     * Test the property 'piece'
     */
    @Test
    public void pieceTest() {
        // TODO: test piece
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'outstandingTotal'
     */
    @Test
    public void outstandingTotalTest() {
        // TODO: test outstandingTotal
    }

    /**
     * Test the property 'bonusMalusTotal'
     */
    @Test
    public void bonusMalusTotalTest() {
        // TODO: test bonusMalusTotal
    }

}
