/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.00.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for Repartitionbyrate
 */
public class RepartitionbyrateTest {
    private final Repartitionbyrate model = new Repartitionbyrate();

    /**
     * Model tests for Repartitionbyrate
     */
    @Test
    public void testRepartitionbyrate() {
        // TODO: test Repartitionbyrate
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'invoice'
     */
    @Test
    public void invoiceTest() {
        // TODO: test invoice
    }

    /**
     * Test the property 'vat'
     */
    @Test
    public void vatTest() {
        // TODO: test vat
    }

    /**
     * Test the property 'vatBase'
     */
    @Test
    public void vatBaseTest() {
        // TODO: test vatBase
    }

    /**
     * Test the property 'totalVat'
     */
    @Test
    public void totalVatTest() {
        // TODO: test totalVat
    }

    /**
     * Test the property 'vatRate'
     */
    @Test
    public void vatRateTest() {
        // TODO: test vatRate
    }

    /**
     * Test the property 'vat2Base'
     */
    @Test
    public void vat2BaseTest() {
        // TODO: test vat2Base
    }

    /**
     * Test the property 'totalVat2'
     */
    @Test
    public void totalVat2Test() {
        // TODO: test totalVat2
    }

    /**
     * Test the property 'vat2Rate'
     */
    @Test
    public void vat2RateTest() {
        // TODO: test vat2Rate
    }

    /**
     * Test the property 'vatCodeType'
     */
    @Test
    public void vatCodeTypeTest() {
        // TODO: test vatCodeType
    }

    /**
     * Test the property 'vatTypeLabel'
     */
    @Test
    public void vatTypeLabelTest() {
        // TODO: test vatTypeLabel
    }

    /**
     * Test the property 'vatCodeTypeIds'
     */
    @Test
    public void vatCodeTypeIdsTest() {
        // TODO: test vatCodeTypeIds
    }

    /**
     * Test the property 'vatReasonExempt'
     */
    @Test
    public void vatReasonExemptTest() {
        // TODO: test vatReasonExempt
    }

    /**
     * Test the property 'vatReasonExemptCode'
     */
    @Test
    public void vatReasonExemptCodeTest() {
        // TODO: test vatReasonExemptCode
    }

    /**
     * Test the property 'extraData'
     */
    @Test
    public void extraDataTest() {
        // TODO: test extraData
    }

}
