/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.00.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for SalesStep
 */
public class SalesStepTest {
    private final SalesStep model = new SalesStep();

    /**
     * Model tests for SalesStep
     */
    @Test
    public void testSalesStep() {
        // TODO: test SalesStep
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'salesCycle'
     */
    @Test
    public void salesCycleTest() {
        // TODO: test salesCycle
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'label1'
     */
    @Test
    public void label1Test() {
        // TODO: test label1
    }

    /**
     * Test the property 'label2'
     */
    @Test
    public void label2Test() {
        // TODO: test label2
    }

    /**
     * Test the property 'label3'
     */
    @Test
    public void label3Test() {
        // TODO: test label3
    }

    /**
     * Test the property 'label4'
     */
    @Test
    public void label4Test() {
        // TODO: test label4
    }

    /**
     * Test the property 'actionType'
     */
    @Test
    public void actionTypeTest() {
        // TODO: test actionType
    }

    /**
     * Test the property 'order'
     */
    @Test
    public void orderTest() {
        // TODO: test order
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'spancoStep'
     */
    @Test
    public void spancoStepTest() {
        // TODO: test spancoStep
    }

    /**
     * Test the property 'extraData'
     */
    @Test
    public void extraDataTest() {
        // TODO: test extraData
    }

}
