/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServletContextClassLoaderParentDefinedPackagesInner
 */
public class ServletContextClassLoaderParentDefinedPackagesInnerTest {
    private final ServletContextClassLoaderParentDefinedPackagesInner model = new ServletContextClassLoaderParentDefinedPackagesInner();

    /**
     * Model tests for ServletContextClassLoaderParentDefinedPackagesInner
     */
    @Test
    public void testServletContextClassLoaderParentDefinedPackagesInner() {
        // TODO: test ServletContextClassLoaderParentDefinedPackagesInner
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'annotations'
     */
    @Test
    public void annotationsTest() {
        // TODO: test annotations
    }

    /**
     * Test the property 'declaredAnnotations'
     */
    @Test
    public void declaredAnnotationsTest() {
        // TODO: test declaredAnnotations
    }

    /**
     * Test the property 'sealed'
     */
    @Test
    public void sealedTest() {
        // TODO: test sealed
    }

    /**
     * Test the property 'specificationTitle'
     */
    @Test
    public void specificationTitleTest() {
        // TODO: test specificationTitle
    }

    /**
     * Test the property 'specificationVersion'
     */
    @Test
    public void specificationVersionTest() {
        // TODO: test specificationVersion
    }

    /**
     * Test the property 'specificationVendor'
     */
    @Test
    public void specificationVendorTest() {
        // TODO: test specificationVendor
    }

    /**
     * Test the property 'implementationTitle'
     */
    @Test
    public void implementationTitleTest() {
        // TODO: test implementationTitle
    }

    /**
     * Test the property 'implementationVersion'
     */
    @Test
    public void implementationVersionTest() {
        // TODO: test implementationVersion
    }

    /**
     * Test the property 'implementationVendor'
     */
    @Test
    public void implementationVendorTest() {
        // TODO: test implementationVendor
    }

}
