/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ServletContextClassLoaderParentUnnamedModule
 */
public class ServletContextClassLoaderParentUnnamedModuleTest {
    private final ServletContextClassLoaderParentUnnamedModule model = new ServletContextClassLoaderParentUnnamedModule();

    /**
     * Model tests for ServletContextClassLoaderParentUnnamedModule
     */
    @Test
    public void testServletContextClassLoaderParentUnnamedModule() {
        // TODO: test ServletContextClassLoaderParentUnnamedModule
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'named'
     */
    @Test
    public void namedTest() {
        // TODO: test named
    }

    /**
     * Test the property 'annotations'
     */
    @Test
    public void annotationsTest() {
        // TODO: test annotations
    }

    /**
     * Test the property 'declaredAnnotations'
     */
    @Test
    public void declaredAnnotationsTest() {
        // TODO: test declaredAnnotations
    }

    /**
     * Test the property 'packages'
     */
    @Test
    public void packagesTest() {
        // TODO: test packages
    }

    /**
     * Test the property 'nativeAccessEnabled'
     */
    @Test
    public void nativeAccessEnabledTest() {
        // TODO: test nativeAccessEnabled
    }

    /**
     * Test the property 'layer'
     */
    @Test
    public void layerTest() {
        // TODO: test layer
    }

}
