/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.everwin.sx.client.model.SpecificData;
import fr.everwin.sx.client.model.SupplierInvoiceDataLink;
import fr.everwin.sx.client.model.SupplierSettlementDataLink;
import fr.everwin.sx.client.model.SupplierSettlementLineMultiCurrency;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SupplierSettlementLine
 */
public class SupplierSettlementLineTest {
    private final SupplierSettlementLine model = new SupplierSettlementLine();

    /**
     * Model tests for SupplierSettlementLine
     */
    @Test
    public void testSupplierSettlementLine() {
        // TODO: test SupplierSettlementLine
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'supplierSettlement'
     */
    @Test
    public void supplierSettlementTest() {
        // TODO: test supplierSettlement
    }

    /**
     * Test the property 'supplierInvoice'
     */
    @Test
    public void supplierInvoiceTest() {
        // TODO: test supplierInvoice
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'extraData'
     */
    @Test
    public void extraDataTest() {
        // TODO: test extraData
    }

}
