/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.everwin.sx.client.model.CompanyAccountDataLink;
import fr.everwin.sx.client.model.CompanyDataLink;
import fr.everwin.sx.client.model.ContactResponsibilityDataLink;
import fr.everwin.sx.client.model.EmployeeDataLink;
import fr.everwin.sx.client.model.EntityDataLink;
import fr.everwin.sx.client.model.ProjectDataLink;
import fr.everwin.sx.client.model.SpecificData;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonFormat;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SupplierOrder
 */
public class SupplierOrderTest {
    private final SupplierOrder model = new SupplierOrder();

    /**
     * Model tests for SupplierOrder
     */
    @Test
    public void testSupplierOrder() {
        // TODO: test SupplierOrder
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'validationStep'
     */
    @Test
    public void validationStepTest() {
        // TODO: test validationStep
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'supplier'
     */
    @Test
    public void supplierTest() {
        // TODO: test supplier
    }

    /**
     * Test the property 'contact'
     */
    @Test
    public void contactTest() {
        // TODO: test contact
    }

    /**
     * Test the property 'entity'
     */
    @Test
    public void entityTest() {
        // TODO: test entity
    }

    /**
     * Test the property 'financialEntity'
     */
    @Test
    public void financialEntityTest() {
        // TODO: test financialEntity
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'issuer'
     */
    @Test
    public void issuerTest() {
        // TODO: test issuer
    }

    /**
     * Test the property 'supplierAccount'
     */
    @Test
    public void supplierAccountTest() {
        // TODO: test supplierAccount
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

    /**
     * Test the property 'deliveryDate'
     */
    @Test
    public void deliveryDateTest() {
        // TODO: test deliveryDate
    }

    /**
     * Test the property 'supplierReference'
     */
    @Test
    public void supplierReferenceTest() {
        // TODO: test supplierReference
    }

    /**
     * Test the property 'estimateReference'
     */
    @Test
    public void estimateReferenceTest() {
        // TODO: test estimateReference
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'totalWithoutVat'
     */
    @Test
    public void totalWithoutVatTest() {
        // TODO: test totalWithoutVat
    }

    /**
     * Test the property 'deliveryAddress'
     */
    @Test
    public void deliveryAddressTest() {
        // TODO: test deliveryAddress
    }

    /**
     * Test the property 'deliveryStatus'
     */
    @Test
    public void deliveryStatusTest() {
        // TODO: test deliveryStatus
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'updatedOnTime'
     */
    @Test
    public void updatedOnTimeTest() {
        // TODO: test updatedOnTime
    }

    /**
     * Test the property 'createdOnTime'
     */
    @Test
    public void createdOnTimeTest() {
        // TODO: test createdOnTime
    }

    /**
     * Test the property 'extraData'
     */
    @Test
    public void extraDataTest() {
        // TODO: test extraData
    }

}
