/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.everwin.sx.client.model.Access;
import fr.everwin.sx.client.model.EmployeeDataLink;
import fr.everwin.sx.client.model.ProjectDataLink;
import fr.everwin.sx.client.model.ProjectLineDataLink;
import fr.everwin.sx.client.model.ProjectSubLineDataLink;
import fr.everwin.sx.client.model.SpecificData;
import fr.everwin.sx.client.model.TimesheetDataLink;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonFormat;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TimesheetLine
 */
public class TimesheetLineTest {
    private final TimesheetLine model = new TimesheetLine();

    /**
     * Model tests for TimesheetLine
     */
    @Test
    public void testTimesheetLine() {
        // TODO: test TimesheetLine
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'timeSheet'
     */
    @Test
    public void timeSheetTest() {
        // TODO: test timeSheet
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'projectLine'
     */
    @Test
    public void projectLineTest() {
        // TODO: test projectLine
    }

    /**
     * Test the property 'projectSubLine'
     */
    @Test
    public void projectSubLineTest() {
        // TODO: test projectSubLine
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'quantityInDay'
     */
    @Test
    public void quantityInDayTest() {
        // TODO: test quantityInDay
    }

    /**
     * Test the property 'dayDecode'
     */
    @Test
    public void dayDecodeTest() {
        // TODO: test dayDecode
    }

    /**
     * Test the property 'displayProjectSubLine'
     */
    @Test
    public void displayProjectSubLineTest() {
        // TODO: test displayProjectSubLine
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'commentAuthor'
     */
    @Test
    public void commentAuthorTest() {
        // TODO: test commentAuthor
    }

    /**
     * Test the property 'access'
     */
    @Test
    public void accessTest() {
        // TODO: test access
    }

    /**
     * Test the property 'extraData'
     */
    @Test
    public void extraDataTest() {
        // TODO: test extraData
    }

}
