/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.everwin.sx.client.model.TimesheetLine;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TimesheetLineList
 */
public class TimesheetLineListTest {
    private final TimesheetLineList model = new TimesheetLineList();

    /**
     * Model tests for TimesheetLineList
     */
    @Test
    public void testTimesheetLineList() {
        // TODO: test TimesheetLineList
    }

    /**
     * Test the property 'timesheetlines'
     */
    @Test
    public void timesheetlinesTest() {
        // TODO: test timesheetlines
    }

    /**
     * Test the property 'selflink'
     */
    @Test
    public void selflinkTest() {
        // TODO: test selflink
    }

}
