/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TurnoverSizeList
 */
public class TurnoverSizeListTest {
    private final TurnoverSizeList model = new TurnoverSizeList();

    /**
     * Model tests for TurnoverSizeList
     */
    @Test
    public void testTurnoverSizeList() {
        // TODO: test TurnoverSizeList
    }

    /**
     * Test the property 'turnoversizes'
     */
    @Test
    public void turnoversizesTest() {
        // TODO: test turnoversizes
    }

}
