/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.00.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for Workcontracttype
 */
public class WorkcontracttypeTest {
    private final Workcontracttype model = new Workcontracttype();

    /**
     * Model tests for Workcontracttype
     */
    @Test
    public void testWorkcontracttype() {
        // TODO: test Workcontracttype
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'label1'
     */
    @Test
    public void label1Test() {
        // TODO: test label1
    }

    /**
     * Test the property 'label2'
     */
    @Test
    public void label2Test() {
        // TODO: test label2
    }

    /**
     * Test the property 'label3'
     */
    @Test
    public void label3Test() {
        // TODO: test label3
    }

    /**
     * Test the property 'label4'
     */
    @Test
    public void label4Test() {
        // TODO: test label4
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'visibility'
     */
    @Test
    public void visibilityTest() {
        // TODO: test visibility
    }

    /**
     * Test the property 'entities'
     */
    @Test
    public void entitiesTest() {
        // TODO: test entities
    }

    /**
     * Test the property 'extraData'
     */
    @Test
    public void extraDataTest() {
        // TODO: test extraData
    }

}
