/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * choruspaymentrequestlist
 */
@JsonPropertyOrder({
  ChorusPaymentRequestList.JSON_PROPERTY_CHORUS_PAYMENT_REQUESTS,
  ChorusPaymentRequestList.JSON_PROPERTY_SELFLINK
})
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-10-06T08:58:20.555636300+02:00[Europe/Paris]")
public class ChorusPaymentRequestList {
  public static final String JSON_PROPERTY_CHORUS_PAYMENT_REQUESTS = "chorus-payment-requests";
  private List<ChorusPaymentrequest> chorusPaymentRequests;

  public static final String JSON_PROPERTY_SELFLINK = "selflink";
  private String selflink;

  public ChorusPaymentRequestList() { 
  }

  public ChorusPaymentRequestList chorusPaymentRequests(List<ChorusPaymentrequest> chorusPaymentRequests) {
    this.chorusPaymentRequests = chorusPaymentRequests;
    return this;
  }

  public ChorusPaymentRequestList addChorusPaymentRequestsItem(ChorusPaymentrequest chorusPaymentRequestsItem) {
    if (this.chorusPaymentRequests == null) {
      this.chorusPaymentRequests = new ArrayList<>();
    }
    this.chorusPaymentRequests.add(chorusPaymentRequestsItem);
    return this;
  }

   /**
   * Get chorusPaymentRequests
   * @return chorusPaymentRequests
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHORUS_PAYMENT_REQUESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ChorusPaymentrequest> getChorusPaymentRequests() {
    return chorusPaymentRequests;
  }


  @JsonProperty(JSON_PROPERTY_CHORUS_PAYMENT_REQUESTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChorusPaymentRequests(List<ChorusPaymentrequest> chorusPaymentRequests) {
    this.chorusPaymentRequests = chorusPaymentRequests;
  }


  public ChorusPaymentRequestList selflink(String selflink) {
    this.selflink = selflink;
    return this;
  }

   /**
   * Get selflink
   * @return selflink
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSelflink() {
    return selflink;
  }


  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelflink(String selflink) {
    this.selflink = selflink;
  }


  /**
   * Return true if this ChorusPaymentRequestList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChorusPaymentRequestList chorusPaymentRequestList = (ChorusPaymentRequestList) o;
    return Objects.equals(this.chorusPaymentRequests, chorusPaymentRequestList.chorusPaymentRequests) &&
        Objects.equals(this.selflink, chorusPaymentRequestList.selflink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chorusPaymentRequests, selflink);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChorusPaymentRequestList {\n");
    sb.append("    chorusPaymentRequests: ").append(toIndentedString(chorusPaymentRequests)).append("\n");
    sb.append("    selflink: ").append(toIndentedString(selflink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

