/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.everwin.sx.client.model.CompanyDataLink;
import fr.everwin.sx.client.model.CountryDataLink;
import fr.everwin.sx.client.model.DataLink;
import fr.everwin.sx.client.model.EmployeeDataLink;
import fr.everwin.sx.client.model.PersonDataLink;
import fr.everwin.sx.client.model.SpecificData;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import fr.everwin.sx.client.JSON;


/**
 * Contactresponsibility
 */
@JsonPropertyOrder({
  Contactresponsibility.JSON_PROPERTY_ID,
  Contactresponsibility.JSON_PROPERTY_COMPANY,
  Contactresponsibility.JSON_PROPERTY_PERSON,
  Contactresponsibility.JSON_PROPERTY_CIVILITY,
  Contactresponsibility.JSON_PROPERTY_FIRST_NAME,
  Contactresponsibility.JSON_PROPERTY_LAST_NAME,
  Contactresponsibility.JSON_PROPERTY_FUNCTION,
  Contactresponsibility.JSON_PROPERTY_FUNCTION_TYPE,
  Contactresponsibility.JSON_PROPERTY_ASSIGNED_TO,
  Contactresponsibility.JSON_PROPERTY_PHONE,
  Contactresponsibility.JSON_PROPERTY_MOBILE,
  Contactresponsibility.JSON_PROPERTY_FAX,
  Contactresponsibility.JSON_PROPERTY_EMAIL,
  Contactresponsibility.JSON_PROPERTY_ACCEPTS_EMAIL,
  Contactresponsibility.JSON_PROPERTY_LEFT_COMPANY,
  Contactresponsibility.JSON_PROPERTY_SERVICE,
  Contactresponsibility.JSON_PROPERTY_ADDRESS,
  Contactresponsibility.JSON_PROPERTY_ADDRESS2,
  Contactresponsibility.JSON_PROPERTY_ADDRESS3,
  Contactresponsibility.JSON_PROPERTY_POSTAL_CODE,
  Contactresponsibility.JSON_PROPERTY_CITY,
  Contactresponsibility.JSON_PROPERTY_COUNTRY,
  Contactresponsibility.JSON_PROPERTY_COMMENT,
  Contactresponsibility.JSON_PROPERTY_UPDATED_ON_TIME,
  Contactresponsibility.JSON_PROPERTY_CREATED_ON_TIME,
  Contactresponsibility.JSON_PROPERTY_UPDATED_BY,
  Contactresponsibility.JSON_PROPERTY_EXTRA_DATA
})
@JsonTypeName("contactresponsibility")
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-05-22T08:24:46.022483900+02:00[Europe/Paris]")
public class Contactresponsibility {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_COMPANY = "company";
  private CompanyDataLink company;

  public static final String JSON_PROPERTY_PERSON = "person";
  private PersonDataLink person;

  /**
   * Civility of the contact.
   */
  public enum CivilityEnum {
    NUMBER_1(1),
    
    NUMBER_2(2),
    
    NUMBER_3(3);

    private Integer value;

    CivilityEnum(Integer value) {
      this.value = value;
    }

    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CivilityEnum fromValue(Integer value) {
      for (CivilityEnum b : CivilityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CIVILITY = "civility";
  private CivilityEnum civility;

  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  private String lastName;

  public static final String JSON_PROPERTY_FUNCTION = "function";
  private String function;

  public static final String JSON_PROPERTY_FUNCTION_TYPE = "functionType";
  private DataLink functionType;

  public static final String JSON_PROPERTY_ASSIGNED_TO = "assignedTo";
  private EmployeeDataLink assignedTo;

  public static final String JSON_PROPERTY_PHONE = "phone";
  private String phone;

  public static final String JSON_PROPERTY_MOBILE = "mobile";
  private String mobile;

  public static final String JSON_PROPERTY_FAX = "fax";
  private String fax;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  /**
   * Contact accepts or not e-mail for marketing campaigns.  0 : No, 1 : Yes.
   */
  public enum AcceptsEmailEnum {
    NUMBER_0(0),
    
    NUMBER_1(1);

    private Integer value;

    AcceptsEmailEnum(Integer value) {
      this.value = value;
    }

    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AcceptsEmailEnum fromValue(Integer value) {
      for (AcceptsEmailEnum b : AcceptsEmailEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACCEPTS_EMAIL = "acceptsEmail";
  private AcceptsEmailEnum acceptsEmail;

  /**
   * Indicates if the contact is still in the company or not. 0 : No, 1 : Yes.
   */
  public enum LeftCompanyEnum {
    NUMBER_0(0),
    
    NUMBER_1(1);

    private Integer value;

    LeftCompanyEnum(Integer value) {
      this.value = value;
    }

    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LeftCompanyEnum fromValue(Integer value) {
      for (LeftCompanyEnum b : LeftCompanyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LEFT_COMPANY = "leftCompany";
  private LeftCompanyEnum leftCompany;

  public static final String JSON_PROPERTY_SERVICE = "service";
  private String service;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private String address;

  public static final String JSON_PROPERTY_ADDRESS2 = "address2";
  private String address2;

  public static final String JSON_PROPERTY_ADDRESS3 = "address3";
  private String address3;

  public static final String JSON_PROPERTY_POSTAL_CODE = "postalCode";
  private String postalCode;

  public static final String JSON_PROPERTY_CITY = "city";
  private String city;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private CountryDataLink country;

  public static final String JSON_PROPERTY_COMMENT = "comment";
  private String comment;

  public static final String JSON_PROPERTY_UPDATED_ON_TIME = "updatedOnTime";
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "CET")
  private java.time.LocalDateTime updatedOnTime;

  public static final String JSON_PROPERTY_CREATED_ON_TIME = "createdOnTime";
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "CET")
  private java.time.LocalDateTime createdOnTime;

  public static final String JSON_PROPERTY_UPDATED_BY = "updatedBy";
  private String updatedBy;

  public static final String JSON_PROPERTY_EXTRA_DATA = "extraData";
  private List<SpecificData> extraData;

  public Contactresponsibility() { 
  }

  public Contactresponsibility id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * id of the object
   * @return id
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(Long id) {
    this.id = id;
  }


  public Contactresponsibility company(CompanyDataLink company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CompanyDataLink getCompany() {
    return company;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompany(CompanyDataLink company) {
    this.company = company;
  }


  public Contactresponsibility person(PersonDataLink person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PersonDataLink getPerson() {
    return person;
  }


  @JsonProperty(JSON_PROPERTY_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPerson(PersonDataLink person) {
    this.person = person;
  }


  public Contactresponsibility civility(CivilityEnum civility) {
    this.civility = civility;
    return this;
  }

   /**
   * Civility of the contact.
   * @return civility
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CIVILITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CivilityEnum getCivility() {
    return civility;
  }


  @JsonProperty(JSON_PROPERTY_CIVILITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCivility(CivilityEnum civility) {
    this.civility = civility;
  }


  public Contactresponsibility firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * First name of the contact
   * @return firstName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public Contactresponsibility lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Last name of the contact
   * @return lastName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastName() {
    return lastName;
  }


  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public Contactresponsibility function(String function) {
    this.function = function;
    return this;
  }

   /**
   * The contact&#39;s title within his or her company
   * @return function
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUNCTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFunction() {
    return function;
  }


  @JsonProperty(JSON_PROPERTY_FUNCTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFunction(String function) {
    this.function = function;
  }


  public Contactresponsibility functionType(DataLink functionType) {
    this.functionType = functionType;
    return this;
  }

   /**
   * Get functionType
   * @return functionType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUNCTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DataLink getFunctionType() {
    return functionType;
  }


  @JsonProperty(JSON_PROPERTY_FUNCTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFunctionType(DataLink functionType) {
    this.functionType = functionType;
  }


  public Contactresponsibility assignedTo(EmployeeDataLink assignedTo) {
    this.assignedTo = assignedTo;
    return this;
  }

   /**
   * Get assignedTo
   * @return assignedTo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASSIGNED_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EmployeeDataLink getAssignedTo() {
    return assignedTo;
  }


  @JsonProperty(JSON_PROPERTY_ASSIGNED_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssignedTo(EmployeeDataLink assignedTo) {
    this.assignedTo = assignedTo;
  }


  public Contactresponsibility phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Direct phone number of the contact
   * @return phone
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(String phone) {
    this.phone = phone;
  }


  public Contactresponsibility mobile(String mobile) {
    this.mobile = mobile;
    return this;
  }

   /**
   * Mobile phone number of the contact
   * @return mobile
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MOBILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMobile() {
    return mobile;
  }


  @JsonProperty(JSON_PROPERTY_MOBILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMobile(String mobile) {
    this.mobile = mobile;
  }


  public Contactresponsibility fax(String fax) {
    this.fax = fax;
    return this;
  }

   /**
   * Fax number of the contact
   * @return fax
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFax() {
    return fax;
  }


  @JsonProperty(JSON_PROPERTY_FAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFax(String fax) {
    this.fax = fax;
  }


  public Contactresponsibility email(String email) {
    this.email = email;
    return this;
  }

   /**
   * E-mail of the contact
   * @return email
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(String email) {
    this.email = email;
  }


  public Contactresponsibility acceptsEmail(AcceptsEmailEnum acceptsEmail) {
    this.acceptsEmail = acceptsEmail;
    return this;
  }

   /**
   * Contact accepts or not e-mail for marketing campaigns.  0 : No, 1 : Yes.
   * @return acceptsEmail
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCEPTS_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AcceptsEmailEnum getAcceptsEmail() {
    return acceptsEmail;
  }


  @JsonProperty(JSON_PROPERTY_ACCEPTS_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcceptsEmail(AcceptsEmailEnum acceptsEmail) {
    this.acceptsEmail = acceptsEmail;
  }


  public Contactresponsibility leftCompany(LeftCompanyEnum leftCompany) {
    this.leftCompany = leftCompany;
    return this;
  }

   /**
   * Indicates if the contact is still in the company or not. 0 : No, 1 : Yes.
   * @return leftCompany
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEFT_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LeftCompanyEnum getLeftCompany() {
    return leftCompany;
  }


  @JsonProperty(JSON_PROPERTY_LEFT_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeftCompany(LeftCompanyEnum leftCompany) {
    this.leftCompany = leftCompany;
  }


  public Contactresponsibility service(String service) {
    this.service = service;
    return this;
  }

   /**
   * Service of the contact
   * @return service
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getService() {
    return service;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setService(String service) {
    this.service = service;
  }


  public Contactresponsibility address(String address) {
    this.address = address;
    return this;
  }

   /**
   * First address line of the contact (only if different from company adress)
   * @return address
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(String address) {
    this.address = address;
  }


  public Contactresponsibility address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * Second address line
   * @return address2
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress2() {
    return address2;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress2(String address2) {
    this.address2 = address2;
  }


  public Contactresponsibility address3(String address3) {
    this.address3 = address3;
    return this;
  }

   /**
   * Third adress line
   * @return address3
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress3() {
    return address3;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress3(String address3) {
    this.address3 = address3;
  }


  public Contactresponsibility postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Postal code of the contact
   * @return postalCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPostalCode() {
    return postalCode;
  }


  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public Contactresponsibility city(String city) {
    this.city = city;
    return this;
  }

   /**
   * City of the contact
   * @return city
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(String city) {
    this.city = city;
  }


  public Contactresponsibility country(CountryDataLink country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CountryDataLink getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(CountryDataLink country) {
    this.country = country;
  }


  public Contactresponsibility comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Comments for the contact
   * @return comment
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComment() {
    return comment;
  }


  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComment(String comment) {
    this.comment = comment;
  }


  public Contactresponsibility updatedOnTime(java.time.LocalDateTime updatedOnTime) {
    this.updatedOnTime = updatedOnTime;
    return this;
  }

   /**
   * Date &amp; time of the last update of the contact
   * @return updatedOnTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_ON_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.LocalDateTime getUpdatedOnTime() {
    return updatedOnTime;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_ON_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedOnTime(java.time.LocalDateTime updatedOnTime) {
    this.updatedOnTime = updatedOnTime;
  }


  public Contactresponsibility createdOnTime(java.time.LocalDateTime createdOnTime) {
    this.createdOnTime = createdOnTime;
    return this;
  }

   /**
   * Date &amp; time of creation of the contact
   * @return createdOnTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_ON_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.LocalDateTime getCreatedOnTime() {
    return createdOnTime;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_ON_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedOnTime(java.time.LocalDateTime createdOnTime) {
    this.createdOnTime = createdOnTime;
  }


  public Contactresponsibility updatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * Login of the user doing the last update on the contact
   * @return updatedBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdatedBy() {
    return updatedBy;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
  }


  public Contactresponsibility extraData(List<SpecificData> extraData) {
    this.extraData = extraData;
    return this;
  }

  public Contactresponsibility addExtraDataItem(SpecificData extraDataItem) {
    if (this.extraData == null) {
      this.extraData = new ArrayList<>();
    }
    this.extraData.add(extraDataItem);
    return this;
  }

   /**
   * Extra data of the company. For more information, see Extra data section
   * @return extraData
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTRA_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SpecificData> getExtraData() {
    return extraData;
  }


  @JsonProperty(JSON_PROPERTY_EXTRA_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtraData(List<SpecificData> extraData) {
    this.extraData = extraData;
  }


  /**
   * Return true if this contactresponsibility object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Contactresponsibility contactresponsibility = (Contactresponsibility) o;
    return Objects.equals(this.id, contactresponsibility.id) &&
        Objects.equals(this.company, contactresponsibility.company) &&
        Objects.equals(this.person, contactresponsibility.person) &&
        Objects.equals(this.civility, contactresponsibility.civility) &&
        Objects.equals(this.firstName, contactresponsibility.firstName) &&
        Objects.equals(this.lastName, contactresponsibility.lastName) &&
        Objects.equals(this.function, contactresponsibility.function) &&
        Objects.equals(this.functionType, contactresponsibility.functionType) &&
        Objects.equals(this.assignedTo, contactresponsibility.assignedTo) &&
        Objects.equals(this.phone, contactresponsibility.phone) &&
        Objects.equals(this.mobile, contactresponsibility.mobile) &&
        Objects.equals(this.fax, contactresponsibility.fax) &&
        Objects.equals(this.email, contactresponsibility.email) &&
        Objects.equals(this.acceptsEmail, contactresponsibility.acceptsEmail) &&
        Objects.equals(this.leftCompany, contactresponsibility.leftCompany) &&
        Objects.equals(this.service, contactresponsibility.service) &&
        Objects.equals(this.address, contactresponsibility.address) &&
        Objects.equals(this.address2, contactresponsibility.address2) &&
        Objects.equals(this.address3, contactresponsibility.address3) &&
        Objects.equals(this.postalCode, contactresponsibility.postalCode) &&
        Objects.equals(this.city, contactresponsibility.city) &&
        Objects.equals(this.country, contactresponsibility.country) &&
        Objects.equals(this.comment, contactresponsibility.comment) &&
        Objects.equals(this.updatedOnTime, contactresponsibility.updatedOnTime) &&
        Objects.equals(this.createdOnTime, contactresponsibility.createdOnTime) &&
        Objects.equals(this.updatedBy, contactresponsibility.updatedBy) &&
        Objects.equals(this.extraData, contactresponsibility.extraData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, company, person, civility, firstName, lastName, function, functionType, assignedTo, phone, mobile, fax, email, acceptsEmail, leftCompany, service, address, address2, address3, postalCode, city, country, comment, updatedOnTime, createdOnTime, updatedBy, extraData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Contactresponsibility {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    civility: ").append(toIndentedString(civility)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("    functionType: ").append(toIndentedString(functionType)).append("\n");
    sb.append("    assignedTo: ").append(toIndentedString(assignedTo)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    acceptsEmail: ").append(toIndentedString(acceptsEmail)).append("\n");
    sb.append("    leftCompany: ").append(toIndentedString(leftCompany)).append("\n");
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    address3: ").append(toIndentedString(address3)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    updatedOnTime: ").append(toIndentedString(updatedOnTime)).append("\n");
    sb.append("    createdOnTime: ").append(toIndentedString(createdOnTime)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    extraData: ").append(toIndentedString(extraData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

