/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * CrmQuoteLine
 */
@JsonPropertyOrder({
  CrmQuoteLine.JSON_PROPERTY_ID,
  CrmQuoteLine.JSON_PROPERTY_TYPE,
  CrmQuoteLine.JSON_PROPERTY_RESOURCE,
  CrmQuoteLine.JSON_PROPERTY_REFERENCE,
  CrmQuoteLine.JSON_PROPERTY_COMMENT,
  CrmQuoteLine.JSON_PROPERTY_VAT,
  CrmQuoteLine.JSON_PROPERTY_VAT_RATE,
  CrmQuoteLine.JSON_PROPERTY_VAT2_RATE,
  CrmQuoteLine.JSON_PROPERTY_ORDER,
  CrmQuoteLine.JSON_PROPERTY_EXTRA_DATA,
  CrmQuoteLine.JSON_PROPERTY_QUOTE,
  CrmQuoteLine.JSON_PROPERTY_PARENT,
  CrmQuoteLine.JSON_PROPERTY_OPPORTUNITY,
  CrmQuoteLine.JSON_PROPERTY_PRODUCT,
  CrmQuoteLine.JSON_PROPERTY_LEVEL,
  CrmQuoteLine.JSON_PROPERTY_LEAF,
  CrmQuoteLine.JSON_PROPERTY_UNIT,
  CrmQuoteLine.JSON_PROPERTY_DISCOUNT,
  CrmQuoteLine.JSON_PROPERTY_DISCOUNT_PERCENT,
  CrmQuoteLine.JSON_PROPERTY_REVENUE_QUANTITY,
  CrmQuoteLine.JSON_PROPERTY_REVENUE,
  CrmQuoteLine.JSON_PROPERTY_REVENUE_NET,
  CrmQuoteLine.JSON_PROPERTY_REVENUE_DISCOUNT,
  CrmQuoteLine.JSON_PROPERTY_EXPENDITURE_QUANTITY,
  CrmQuoteLine.JSON_PROPERTY_EXPENDITURE
})
@JsonTypeName("crmQuoteLine")
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-10-06T08:58:20.555636300+02:00[Europe/Paris]")
public class CrmQuoteLine {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_TYPE = "type";
  private RowtypeDataLink type;

  public static final String JSON_PROPERTY_RESOURCE = "resource";
  private QuoteResource resource;

  public static final String JSON_PROPERTY_REFERENCE = "reference";
  private String reference;

  public static final String JSON_PROPERTY_COMMENT = "comment";
  private String comment;

  public static final String JSON_PROPERTY_VAT = "vat";
  private DataLink vat;

  public static final String JSON_PROPERTY_VAT_RATE = "vatRate";
  private Double vatRate;

  public static final String JSON_PROPERTY_VAT2_RATE = "vat2Rate";
  private Double vat2Rate;

  public static final String JSON_PROPERTY_ORDER = "order";
  private Integer order;

  public static final String JSON_PROPERTY_EXTRA_DATA = "extraData";
  private List<SpecificData> extraData;

  public static final String JSON_PROPERTY_QUOTE = "quote";
  private CRMQuoteDataLink quote;

  public static final String JSON_PROPERTY_PARENT = "parent";
  private CRMQuoteLineDataLink parent;

  public static final String JSON_PROPERTY_OPPORTUNITY = "opportunity";
  private OpportunityDataLink opportunity;

  public static final String JSON_PROPERTY_PRODUCT = "product";
  private ProductDataLink product;

  public static final String JSON_PROPERTY_LEVEL = "level";
  private Integer level;

  public static final String JSON_PROPERTY_LEAF = "leaf";
  private Boolean leaf;

  public static final String JSON_PROPERTY_UNIT = "unit";
  private DataLink unit;

  public static final String JSON_PROPERTY_DISCOUNT = "discount";
  private Double discount;

  public static final String JSON_PROPERTY_DISCOUNT_PERCENT = "discountPercent";
  private Double discountPercent;

  public static final String JSON_PROPERTY_REVENUE_QUANTITY = "revenueQuantity";
  private Double revenueQuantity;

  public static final String JSON_PROPERTY_REVENUE = "revenue";
  private QuoteLineDebitCredit revenue;

  public static final String JSON_PROPERTY_REVENUE_NET = "revenueNet";
  private QuoteLineDebitCredit revenueNet;

  public static final String JSON_PROPERTY_REVENUE_DISCOUNT = "revenueDiscount";
  private QuoteLineDebitCredit revenueDiscount;

  public static final String JSON_PROPERTY_EXPENDITURE_QUANTITY = "expenditureQuantity";
  private Double expenditureQuantity;

  public static final String JSON_PROPERTY_EXPENDITURE = "expenditure";
  private QuoteLineDebitCredit expenditure;

  public CrmQuoteLine() { 
  }

  @JsonCreator
  public CrmQuoteLine(
    @JsonProperty(JSON_PROPERTY_LEVEL) Integer level, 
    @JsonProperty(JSON_PROPERTY_LEAF) Boolean leaf
  ) {
    this();
    this.level = level;
    this.leaf = leaf;
  }

  public CrmQuoteLine id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * id of the object
   * @return id
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(Long id) {
    this.id = id;
  }


  public CrmQuoteLine type(RowtypeDataLink type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RowtypeDataLink getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(RowtypeDataLink type) {
    this.type = type;
  }


  public CrmQuoteLine resource(QuoteResource resource) {
    this.resource = resource;
    return this;
  }

   /**
   * Get resource
   * @return resource
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public QuoteResource getResource() {
    return resource;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResource(QuoteResource resource) {
    this.resource = resource;
  }


  public CrmQuoteLine reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Reference of the quote line
   * @return reference
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReference() {
    return reference;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReference(String reference) {
    this.reference = reference;
  }


  public CrmQuoteLine comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Comment of the quote line
   * @return comment
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComment() {
    return comment;
  }


  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComment(String comment) {
    this.comment = comment;
  }


  public CrmQuoteLine vat(DataLink vat) {
    this.vat = vat;
    return this;
  }

   /**
   * Get vat
   * @return vat
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DataLink getVat() {
    return vat;
  }


  @JsonProperty(JSON_PROPERTY_VAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVat(DataLink vat) {
    this.vat = vat;
  }


  public CrmQuoteLine vatRate(Double vatRate) {
    this.vatRate = vatRate;
    return this;
  }

   /**
   * VAT rate of the quote line
   * @return vatRate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getVatRate() {
    return vatRate;
  }


  @JsonProperty(JSON_PROPERTY_VAT_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVatRate(Double vatRate) {
    this.vatRate = vatRate;
  }


  public CrmQuoteLine vat2Rate(Double vat2Rate) {
    this.vat2Rate = vat2Rate;
    return this;
  }

   /**
   * VAT rate 2 of the quote line
   * @return vat2Rate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT2_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getVat2Rate() {
    return vat2Rate;
  }


  @JsonProperty(JSON_PROPERTY_VAT2_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVat2Rate(Double vat2Rate) {
    this.vat2Rate = vat2Rate;
  }


  public CrmQuoteLine order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Order of the quote line
   * @return order
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOrder() {
    return order;
  }


  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrder(Integer order) {
    this.order = order;
  }


  public CrmQuoteLine extraData(List<SpecificData> extraData) {
    this.extraData = extraData;
    return this;
  }

  public CrmQuoteLine addExtraDataItem(SpecificData extraDataItem) {
    if (this.extraData == null) {
      this.extraData = new ArrayList<>();
    }
    this.extraData.add(extraDataItem);
    return this;
  }

   /**
   * Extra data of the crm quote. For more information, see Extra data section
   * @return extraData
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTRA_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SpecificData> getExtraData() {
    return extraData;
  }


  @JsonProperty(JSON_PROPERTY_EXTRA_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtraData(List<SpecificData> extraData) {
    this.extraData = extraData;
  }


  public CrmQuoteLine quote(CRMQuoteDataLink quote) {
    this.quote = quote;
    return this;
  }

   /**
   * Get quote
   * @return quote
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QUOTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CRMQuoteDataLink getQuote() {
    return quote;
  }


  @JsonProperty(JSON_PROPERTY_QUOTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuote(CRMQuoteDataLink quote) {
    this.quote = quote;
  }


  public CrmQuoteLine parent(CRMQuoteLineDataLink parent) {
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CRMQuoteLineDataLink getParent() {
    return parent;
  }


  @JsonProperty(JSON_PROPERTY_PARENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParent(CRMQuoteLineDataLink parent) {
    this.parent = parent;
  }


  public CrmQuoteLine opportunity(OpportunityDataLink opportunity) {
    this.opportunity = opportunity;
    return this;
  }

   /**
   * Get opportunity
   * @return opportunity
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPPORTUNITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OpportunityDataLink getOpportunity() {
    return opportunity;
  }


  @JsonProperty(JSON_PROPERTY_OPPORTUNITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpportunity(OpportunityDataLink opportunity) {
    this.opportunity = opportunity;
  }


  public CrmQuoteLine product(ProductDataLink product) {
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRODUCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProductDataLink getProduct() {
    return product;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProduct(ProductDataLink product) {
    this.product = product;
  }


   /**
   * Level of the quote line
   * @return level
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLevel() {
    return level;
  }




   /**
   * Order of the quote line
   * @return leaf
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEAF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLeaf() {
    return leaf;
  }




  public CrmQuoteLine unit(DataLink unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DataLink getUnit() {
    return unit;
  }


  @JsonProperty(JSON_PROPERTY_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnit(DataLink unit) {
    this.unit = unit;
  }


  public CrmQuoteLine discount(Double discount) {
    this.discount = discount;
    return this;
  }

   /**
   * Discount of the quote line
   * @return discount
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getDiscount() {
    return discount;
  }


  @JsonProperty(JSON_PROPERTY_DISCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiscount(Double discount) {
    this.discount = discount;
  }


  public CrmQuoteLine discountPercent(Double discountPercent) {
    this.discountPercent = discountPercent;
    return this;
  }

   /**
   * Discount in percentage of the quote line
   * @return discountPercent
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISCOUNT_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getDiscountPercent() {
    return discountPercent;
  }


  @JsonProperty(JSON_PROPERTY_DISCOUNT_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiscountPercent(Double discountPercent) {
    this.discountPercent = discountPercent;
  }


  public CrmQuoteLine revenueQuantity(Double revenueQuantity) {
    this.revenueQuantity = revenueQuantity;
    return this;
  }

   /**
   * TurnoverSize quantity of the quote line
   * @return revenueQuantity
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REVENUE_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getRevenueQuantity() {
    return revenueQuantity;
  }


  @JsonProperty(JSON_PROPERTY_REVENUE_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevenueQuantity(Double revenueQuantity) {
    this.revenueQuantity = revenueQuantity;
  }


  public CrmQuoteLine revenue(QuoteLineDebitCredit revenue) {
    this.revenue = revenue;
    return this;
  }

   /**
   * Get revenue
   * @return revenue
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REVENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public QuoteLineDebitCredit getRevenue() {
    return revenue;
  }


  @JsonProperty(JSON_PROPERTY_REVENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevenue(QuoteLineDebitCredit revenue) {
    this.revenue = revenue;
  }


  public CrmQuoteLine revenueNet(QuoteLineDebitCredit revenueNet) {
    this.revenueNet = revenueNet;
    return this;
  }

   /**
   * Get revenueNet
   * @return revenueNet
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REVENUE_NET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public QuoteLineDebitCredit getRevenueNet() {
    return revenueNet;
  }


  @JsonProperty(JSON_PROPERTY_REVENUE_NET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevenueNet(QuoteLineDebitCredit revenueNet) {
    this.revenueNet = revenueNet;
  }


  public CrmQuoteLine revenueDiscount(QuoteLineDebitCredit revenueDiscount) {
    this.revenueDiscount = revenueDiscount;
    return this;
  }

   /**
   * Get revenueDiscount
   * @return revenueDiscount
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REVENUE_DISCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public QuoteLineDebitCredit getRevenueDiscount() {
    return revenueDiscount;
  }


  @JsonProperty(JSON_PROPERTY_REVENUE_DISCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevenueDiscount(QuoteLineDebitCredit revenueDiscount) {
    this.revenueDiscount = revenueDiscount;
  }


  public CrmQuoteLine expenditureQuantity(Double expenditureQuantity) {
    this.expenditureQuantity = expenditureQuantity;
    return this;
  }

   /**
   * Expenditure quantity of the quote line
   * @return expenditureQuantity
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPENDITURE_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getExpenditureQuantity() {
    return expenditureQuantity;
  }


  @JsonProperty(JSON_PROPERTY_EXPENDITURE_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpenditureQuantity(Double expenditureQuantity) {
    this.expenditureQuantity = expenditureQuantity;
  }


  public CrmQuoteLine expenditure(QuoteLineDebitCredit expenditure) {
    this.expenditure = expenditure;
    return this;
  }

   /**
   * Get expenditure
   * @return expenditure
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPENDITURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public QuoteLineDebitCredit getExpenditure() {
    return expenditure;
  }


  @JsonProperty(JSON_PROPERTY_EXPENDITURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpenditure(QuoteLineDebitCredit expenditure) {
    this.expenditure = expenditure;
  }


  /**
   * Return true if this crmQuoteLine object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CrmQuoteLine crmQuoteLine = (CrmQuoteLine) o;
    return Objects.equals(this.id, crmQuoteLine.id) &&
        Objects.equals(this.type, crmQuoteLine.type) &&
        Objects.equals(this.resource, crmQuoteLine.resource) &&
        Objects.equals(this.reference, crmQuoteLine.reference) &&
        Objects.equals(this.comment, crmQuoteLine.comment) &&
        Objects.equals(this.vat, crmQuoteLine.vat) &&
        Objects.equals(this.vatRate, crmQuoteLine.vatRate) &&
        Objects.equals(this.vat2Rate, crmQuoteLine.vat2Rate) &&
        Objects.equals(this.order, crmQuoteLine.order) &&
        Objects.equals(this.extraData, crmQuoteLine.extraData) &&
        Objects.equals(this.quote, crmQuoteLine.quote) &&
        Objects.equals(this.parent, crmQuoteLine.parent) &&
        Objects.equals(this.opportunity, crmQuoteLine.opportunity) &&
        Objects.equals(this.product, crmQuoteLine.product) &&
        Objects.equals(this.level, crmQuoteLine.level) &&
        Objects.equals(this.leaf, crmQuoteLine.leaf) &&
        Objects.equals(this.unit, crmQuoteLine.unit) &&
        Objects.equals(this.discount, crmQuoteLine.discount) &&
        Objects.equals(this.discountPercent, crmQuoteLine.discountPercent) &&
        Objects.equals(this.revenueQuantity, crmQuoteLine.revenueQuantity) &&
        Objects.equals(this.revenue, crmQuoteLine.revenue) &&
        Objects.equals(this.revenueNet, crmQuoteLine.revenueNet) &&
        Objects.equals(this.revenueDiscount, crmQuoteLine.revenueDiscount) &&
        Objects.equals(this.expenditureQuantity, crmQuoteLine.expenditureQuantity) &&
        Objects.equals(this.expenditure, crmQuoteLine.expenditure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, resource, reference, comment, vat, vatRate, vat2Rate, order, extraData, quote, parent, opportunity, product, level, leaf, unit, discount, discountPercent, revenueQuantity, revenue, revenueNet, revenueDiscount, expenditureQuantity, expenditure);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CrmQuoteLine {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    vat: ").append(toIndentedString(vat)).append("\n");
    sb.append("    vatRate: ").append(toIndentedString(vatRate)).append("\n");
    sb.append("    vat2Rate: ").append(toIndentedString(vat2Rate)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    extraData: ").append(toIndentedString(extraData)).append("\n");
    sb.append("    quote: ").append(toIndentedString(quote)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    opportunity: ").append(toIndentedString(opportunity)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    leaf: ").append(toIndentedString(leaf)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    discountPercent: ").append(toIndentedString(discountPercent)).append("\n");
    sb.append("    revenueQuantity: ").append(toIndentedString(revenueQuantity)).append("\n");
    sb.append("    revenue: ").append(toIndentedString(revenue)).append("\n");
    sb.append("    revenueNet: ").append(toIndentedString(revenueNet)).append("\n");
    sb.append("    revenueDiscount: ").append(toIndentedString(revenueDiscount)).append("\n");
    sb.append("    expenditureQuantity: ").append(toIndentedString(expenditureQuantity)).append("\n");
    sb.append("    expenditure: ").append(toIndentedString(expenditure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

