/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * customerorderlist
 */
@JsonPropertyOrder({
  CustomerOrderList.JSON_PROPERTY_CUSTOMERORDERS,
  CustomerOrderList.JSON_PROPERTY_SELFLINK
})
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-10-06T08:58:20.555636300+02:00[Europe/Paris]")
public class CustomerOrderList {
  public static final String JSON_PROPERTY_CUSTOMERORDERS = "customerorders";
  private List<CustomerOrder> customerorders;

  public static final String JSON_PROPERTY_SELFLINK = "selflink";
  private String selflink;

  public CustomerOrderList() { 
  }

  public CustomerOrderList customerorders(List<CustomerOrder> customerorders) {
    this.customerorders = customerorders;
    return this;
  }

  public CustomerOrderList addCustomerordersItem(CustomerOrder customerordersItem) {
    if (this.customerorders == null) {
      this.customerorders = new ArrayList<>();
    }
    this.customerorders.add(customerordersItem);
    return this;
  }

   /**
   * Get customerorders
   * @return customerorders
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOMERORDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CustomerOrder> getCustomerorders() {
    return customerorders;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMERORDERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerorders(List<CustomerOrder> customerorders) {
    this.customerorders = customerorders;
  }


  public CustomerOrderList selflink(String selflink) {
    this.selflink = selflink;
    return this;
  }

   /**
   * Get selflink
   * @return selflink
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSelflink() {
    return selflink;
  }


  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelflink(String selflink) {
    this.selflink = selflink;
  }


  /**
   * Return true if this CustomerOrderList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerOrderList customerOrderList = (CustomerOrderList) o;
    return Objects.equals(this.customerorders, customerOrderList.customerorders) &&
        Objects.equals(this.selflink, customerOrderList.selflink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerorders, selflink);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerOrderList {\n");
    sb.append("    customerorders: ").append(toIndentedString(customerorders)).append("\n");
    sb.append("    selflink: ").append(toIndentedString(selflink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

