/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.Objects;


/**
 * Total without VAT of the customer invoice sub line
 */
@JsonPropertyOrder({
  CustomerInvoiceSubLineDetailMultiCurrency.JSON_PROPERTY_MANAGEMENT,
  CustomerInvoiceSubLineDetailMultiCurrency.JSON_PROPERTY_ACCOUNT,
  CustomerInvoiceSubLineDetailMultiCurrency.JSON_PROPERTY_REPORTING,
  CustomerInvoiceSubLineDetailMultiCurrency.JSON_PROPERTY_LINE_MANAGEMENT
})
@JsonTypeName("customer-invoice-sub-line-detail-multi-currency")
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-10-06T08:58:20.555636300+02:00[Europe/Paris]")
public class CustomerInvoiceSubLineDetailMultiCurrency {
  public static final String JSON_PROPERTY_MANAGEMENT = "management";
  private Double management;

  public static final String JSON_PROPERTY_ACCOUNT = "account";
  private Double account;

  public static final String JSON_PROPERTY_REPORTING = "reporting";
  private Double reporting;

  public static final String JSON_PROPERTY_LINE_MANAGEMENT = "lineManagement";
  private Double lineManagement;

  public CustomerInvoiceSubLineDetailMultiCurrency() { 
  }

  public CustomerInvoiceSubLineDetailMultiCurrency management(Double management) {
    this.management = management;
    return this;
  }

   /**
   * Value in management currency
   * @return management
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getManagement() {
    return management;
  }


  @JsonProperty(JSON_PROPERTY_MANAGEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManagement(Double management) {
    this.management = management;
  }


  public CustomerInvoiceSubLineDetailMultiCurrency account(Double account) {
    this.account = account;
    return this;
  }

   /**
   * Value in account currency
   * @return account
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getAccount() {
    return account;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccount(Double account) {
    this.account = account;
  }


  public CustomerInvoiceSubLineDetailMultiCurrency reporting(Double reporting) {
    this.reporting = reporting;
    return this;
  }

   /**
   * Value in reporting currency
   * @return reporting
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORTING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getReporting() {
    return reporting;
  }


  @JsonProperty(JSON_PROPERTY_REPORTING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReporting(Double reporting) {
    this.reporting = reporting;
  }


  public CustomerInvoiceSubLineDetailMultiCurrency lineManagement(Double lineManagement) {
    this.lineManagement = lineManagement;
    return this;
  }

   /**
   * Value in line management currency
   * @return lineManagement
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINE_MANAGEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLineManagement() {
    return lineManagement;
  }


  @JsonProperty(JSON_PROPERTY_LINE_MANAGEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLineManagement(Double lineManagement) {
    this.lineManagement = lineManagement;
  }


  /**
   * Return true if this customer-invoice-sub-line-detail-multi-currency object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerInvoiceSubLineDetailMultiCurrency customerInvoiceSubLineDetailMultiCurrency = (CustomerInvoiceSubLineDetailMultiCurrency) o;
    return Objects.equals(this.management, customerInvoiceSubLineDetailMultiCurrency.management) &&
        Objects.equals(this.account, customerInvoiceSubLineDetailMultiCurrency.account) &&
        Objects.equals(this.reporting, customerInvoiceSubLineDetailMultiCurrency.reporting) &&
        Objects.equals(this.lineManagement, customerInvoiceSubLineDetailMultiCurrency.lineManagement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(management, account, reporting, lineManagement);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerInvoiceSubLineDetailMultiCurrency {\n");
    sb.append("    management: ").append(toIndentedString(management)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    reporting: ").append(toIndentedString(reporting)).append("\n");
    sb.append("    lineManagement: ").append(toIndentedString(lineManagement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

