/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.everwin.sx.client.model.Equipment;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import fr.everwin.sx.client.JSON;


/**
 * equipmentlist
 */
@JsonPropertyOrder({
  EquipmentList.JSON_PROPERTY_EQUIPMENTS,
  EquipmentList.JSON_PROPERTY_SELFLINK
})
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-05-22T08:24:46.022483900+02:00[Europe/Paris]")
public class EquipmentList {
  public static final String JSON_PROPERTY_EQUIPMENTS = "equipments";
  private List<Equipment> equipments;

  public static final String JSON_PROPERTY_SELFLINK = "selflink";
  private String selflink;

  public EquipmentList() { 
  }

  public EquipmentList equipments(List<Equipment> equipments) {
    this.equipments = equipments;
    return this;
  }

  public EquipmentList addEquipmentsItem(Equipment equipmentsItem) {
    if (this.equipments == null) {
      this.equipments = new ArrayList<>();
    }
    this.equipments.add(equipmentsItem);
    return this;
  }

   /**
   * Get equipments
   * @return equipments
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EQUIPMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Equipment> getEquipments() {
    return equipments;
  }


  @JsonProperty(JSON_PROPERTY_EQUIPMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEquipments(List<Equipment> equipments) {
    this.equipments = equipments;
  }


  public EquipmentList selflink(String selflink) {
    this.selflink = selflink;
    return this;
  }

   /**
   * Get selflink
   * @return selflink
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSelflink() {
    return selflink;
  }


  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelflink(String selflink) {
    this.selflink = selflink;
  }


  /**
   * Return true if this EquipmentList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EquipmentList equipmentList = (EquipmentList) o;
    return Objects.equals(this.equipments, equipmentList.equipments) &&
        Objects.equals(this.selflink, equipmentList.selflink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(equipments, selflink);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EquipmentList {\n");
    sb.append("    equipments: ").append(toIndentedString(equipments)).append("\n");
    sb.append("    selflink: ").append(toIndentedString(selflink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

