/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * expensesheetflowhistorylist
 */
@JsonPropertyOrder({
  ExpenseSheetFlowHistoryList.JSON_PROPERTY_EXPENSESHEETFLOWHISTORIES
})
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-10-06T08:58:20.555636300+02:00[Europe/Paris]")
public class ExpenseSheetFlowHistoryList {
  public static final String JSON_PROPERTY_EXPENSESHEETFLOWHISTORIES = "expensesheetflowhistories";
  private List<ExpenseSheetFlowHistory> expensesheetflowhistories;

  public ExpenseSheetFlowHistoryList() { 
  }

  public ExpenseSheetFlowHistoryList expensesheetflowhistories(List<ExpenseSheetFlowHistory> expensesheetflowhistories) {
    this.expensesheetflowhistories = expensesheetflowhistories;
    return this;
  }

  public ExpenseSheetFlowHistoryList addExpensesheetflowhistoriesItem(ExpenseSheetFlowHistory expensesheetflowhistoriesItem) {
    if (this.expensesheetflowhistories == null) {
      this.expensesheetflowhistories = new ArrayList<>();
    }
    this.expensesheetflowhistories.add(expensesheetflowhistoriesItem);
    return this;
  }

   /**
   * Get expensesheetflowhistories
   * @return expensesheetflowhistories
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPENSESHEETFLOWHISTORIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ExpenseSheetFlowHistory> getExpensesheetflowhistories() {
    return expensesheetflowhistories;
  }


  @JsonProperty(JSON_PROPERTY_EXPENSESHEETFLOWHISTORIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpensesheetflowhistories(List<ExpenseSheetFlowHistory> expensesheetflowhistories) {
    this.expensesheetflowhistories = expensesheetflowhistories;
  }


  /**
   * Return true if this ExpenseSheetFlowHistoryList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpenseSheetFlowHistoryList expenseSheetFlowHistoryList = (ExpenseSheetFlowHistoryList) o;
    return Objects.equals(this.expensesheetflowhistories, expenseSheetFlowHistoryList.expensesheetflowhistories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expensesheetflowhistories);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpenseSheetFlowHistoryList {\n");
    sb.append("    expensesheetflowhistories: ").append(toIndentedString(expensesheetflowhistories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

