/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.everwin.sx.client.model.Lead;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import fr.everwin.sx.client.JSON;


/**
 * leadlist
 */
@JsonPropertyOrder({
  LeadList.JSON_PROPERTY_LEADS,
  LeadList.JSON_PROPERTY_SELFLINK
})
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-05-22T08:24:46.022483900+02:00[Europe/Paris]")
public class LeadList {
  public static final String JSON_PROPERTY_LEADS = "leads";
  private List<Lead> leads;

  public static final String JSON_PROPERTY_SELFLINK = "selflink";
  private String selflink;

  public LeadList() { 
  }

  public LeadList leads(List<Lead> leads) {
    this.leads = leads;
    return this;
  }

  public LeadList addLeadsItem(Lead leadsItem) {
    if (this.leads == null) {
      this.leads = new ArrayList<>();
    }
    this.leads.add(leadsItem);
    return this;
  }

   /**
   * Get leads
   * @return leads
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEADS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Lead> getLeads() {
    return leads;
  }


  @JsonProperty(JSON_PROPERTY_LEADS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeads(List<Lead> leads) {
    this.leads = leads;
  }


  public LeadList selflink(String selflink) {
    this.selflink = selflink;
    return this;
  }

   /**
   * Get selflink
   * @return selflink
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSelflink() {
    return selflink;
  }


  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelflink(String selflink) {
    this.selflink = selflink;
  }


  /**
   * Return true if this LeadList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LeadList leadList = (LeadList) o;
    return Objects.equals(this.leads, leadList.leads) &&
        Objects.equals(this.selflink, leadList.selflink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(leads, selflink);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LeadList {\n");
    sb.append("    leads: ").append(toIndentedString(leads)).append("\n");
    sb.append("    selflink: ").append(toIndentedString(selflink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

