/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * poaquotelist
 */
@JsonPropertyOrder({
  POAQuoteList.JSON_PROPERTY_POAQUOTES
})
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-10-06T08:58:20.555636300+02:00[Europe/Paris]")
public class POAQuoteList {
  public static final String JSON_PROPERTY_POAQUOTES = "poaquotes";
  private List<Poaquote> poaquotes;

  public POAQuoteList() { 
  }

  public POAQuoteList poaquotes(List<Poaquote> poaquotes) {
    this.poaquotes = poaquotes;
    return this;
  }

  public POAQuoteList addPoaquotesItem(Poaquote poaquotesItem) {
    if (this.poaquotes == null) {
      this.poaquotes = new ArrayList<>();
    }
    this.poaquotes.add(poaquotesItem);
    return this;
  }

   /**
   * Get poaquotes
   * @return poaquotes
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POAQUOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Poaquote> getPoaquotes() {
    return poaquotes;
  }


  @JsonProperty(JSON_PROPERTY_POAQUOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPoaquotes(List<Poaquote> poaquotes) {
    this.poaquotes = poaquotes;
  }


  /**
   * Return true if this POAQuoteList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    POAQuoteList poAQuoteList = (POAQuoteList) o;
    return Objects.equals(this.poaquotes, poAQuoteList.poaquotes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(poaquotes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class POAQuoteList {\n");
    sb.append("    poaquotes: ").append(toIndentedString(poaquotes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

