/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.everwin.sx.client.model.ProjectCategories;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import fr.everwin.sx.client.JSON;


/**
 * projectcategorylist
 */
@JsonPropertyOrder({
  ProjectCategoryList.JSON_PROPERTY_PROJECTCATEGORY
})
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-05-22T08:24:46.022483900+02:00[Europe/Paris]")
public class ProjectCategoryList {
  public static final String JSON_PROPERTY_PROJECTCATEGORY = "projectcategory";
  private List<ProjectCategories> projectcategory;

  public ProjectCategoryList() { 
  }

  public ProjectCategoryList projectcategory(List<ProjectCategories> projectcategory) {
    this.projectcategory = projectcategory;
    return this;
  }

  public ProjectCategoryList addProjectcategoryItem(ProjectCategories projectcategoryItem) {
    if (this.projectcategory == null) {
      this.projectcategory = new ArrayList<>();
    }
    this.projectcategory.add(projectcategoryItem);
    return this;
  }

   /**
   * Get projectcategory
   * @return projectcategory
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROJECTCATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ProjectCategories> getProjectcategory() {
    return projectcategory;
  }


  @JsonProperty(JSON_PROPERTY_PROJECTCATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectcategory(List<ProjectCategories> projectcategory) {
    this.projectcategory = projectcategory;
  }


  /**
   * Return true if this ProjectCategoryList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectCategoryList projectCategoryList = (ProjectCategoryList) o;
    return Objects.equals(this.projectcategory, projectCategoryList.projectcategory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectcategory);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectCategoryList {\n");
    sb.append("    projectcategory: ").append(toIndentedString(projectcategory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

