/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * purchaserequestlinelist
 */
@JsonPropertyOrder({
  PurchaseRequestLineList.JSON_PROPERTY_PURCHASEREQUESTLINES,
  PurchaseRequestLineList.JSON_PROPERTY_SELFLINK
})
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-10-06T08:58:20.555636300+02:00[Europe/Paris]")
public class PurchaseRequestLineList {
  public static final String JSON_PROPERTY_PURCHASEREQUESTLINES = "purchaserequestlines";
  private List<PurchaseRequestLine> purchaserequestlines;

  public static final String JSON_PROPERTY_SELFLINK = "selflink";
  private String selflink;

  public PurchaseRequestLineList() { 
  }

  public PurchaseRequestLineList purchaserequestlines(List<PurchaseRequestLine> purchaserequestlines) {
    this.purchaserequestlines = purchaserequestlines;
    return this;
  }

  public PurchaseRequestLineList addPurchaserequestlinesItem(PurchaseRequestLine purchaserequestlinesItem) {
    if (this.purchaserequestlines == null) {
      this.purchaserequestlines = new ArrayList<>();
    }
    this.purchaserequestlines.add(purchaserequestlinesItem);
    return this;
  }

   /**
   * Get purchaserequestlines
   * @return purchaserequestlines
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PURCHASEREQUESTLINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PurchaseRequestLine> getPurchaserequestlines() {
    return purchaserequestlines;
  }


  @JsonProperty(JSON_PROPERTY_PURCHASEREQUESTLINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPurchaserequestlines(List<PurchaseRequestLine> purchaserequestlines) {
    this.purchaserequestlines = purchaserequestlines;
  }


  public PurchaseRequestLineList selflink(String selflink) {
    this.selflink = selflink;
    return this;
  }

   /**
   * Get selflink
   * @return selflink
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSelflink() {
    return selflink;
  }


  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelflink(String selflink) {
    this.selflink = selflink;
  }


  /**
   * Return true if this PurchaseRequestLineList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseRequestLineList purchaseRequestLineList = (PurchaseRequestLineList) o;
    return Objects.equals(this.purchaserequestlines, purchaseRequestLineList.purchaserequestlines) &&
        Objects.equals(this.selflink, purchaseRequestLineList.selflink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(purchaserequestlines, selflink);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseRequestLineList {\n");
    sb.append("    purchaserequestlines: ").append(toIndentedString(purchaserequestlines)).append("\n");
    sb.append("    selflink: ").append(toIndentedString(selflink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

