/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.00.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * Repartitionbyrate
 */
@JsonPropertyOrder({
  Repartitionbyrate.JSON_PROPERTY_ID,
  Repartitionbyrate.JSON_PROPERTY_INVOICE,
  Repartitionbyrate.JSON_PROPERTY_VAT,
  Repartitionbyrate.JSON_PROPERTY_VAT_BASE,
  Repartitionbyrate.JSON_PROPERTY_TOTAL_VAT,
  Repartitionbyrate.JSON_PROPERTY_VAT_RATE,
  Repartitionbyrate.JSON_PROPERTY_VAT2_BASE,
  Repartitionbyrate.JSON_PROPERTY_TOTAL_VAT2,
  Repartitionbyrate.JSON_PROPERTY_VAT2_RATE,
  Repartitionbyrate.JSON_PROPERTY_VAT_CODE_TYPE,
  Repartitionbyrate.JSON_PROPERTY_VAT_TYPE_LABEL,
  Repartitionbyrate.JSON_PROPERTY_VAT_CODE_TYPE_IDS,
  Repartitionbyrate.JSON_PROPERTY_VAT_REASON_EXEMPT,
  Repartitionbyrate.JSON_PROPERTY_VAT_REASON_EXEMPT_CODE,
  Repartitionbyrate.JSON_PROPERTY_EXTRA_DATA
})
@JsonTypeName("repartitionbyrate")
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2026-07-16T11:45:50.162960500+02:00[Europe/Paris]")
public class Repartitionbyrate {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_INVOICE = "invoice";
  private CustomerInvoiceDataLink invoice;

  public static final String JSON_PROPERTY_VAT = "vat";
  private VatDataLink vat;

  public static final String JSON_PROPERTY_VAT_BASE = "vatBase";
  private Double vatBase;

  public static final String JSON_PROPERTY_TOTAL_VAT = "totalVat";
  private Double totalVat;

  public static final String JSON_PROPERTY_VAT_RATE = "vatRate";
  private Double vatRate;

  public static final String JSON_PROPERTY_VAT2_BASE = "vat2Base";
  private Double vat2Base;

  public static final String JSON_PROPERTY_TOTAL_VAT2 = "totalVat2";
  private Double totalVat2;

  public static final String JSON_PROPERTY_VAT2_RATE = "vat2Rate";
  private Double vat2Rate;

  public static final String JSON_PROPERTY_VAT_CODE_TYPE = "vatCodeType";
  private String vatCodeType;

  public static final String JSON_PROPERTY_VAT_TYPE_LABEL = "vatTypeLabel";
  private String vatTypeLabel;

  public static final String JSON_PROPERTY_VAT_CODE_TYPE_IDS = "vatCodeTypeIds";
  private String vatCodeTypeIds;

  public static final String JSON_PROPERTY_VAT_REASON_EXEMPT = "vatReasonExempt";
  private String vatReasonExempt;

  public static final String JSON_PROPERTY_VAT_REASON_EXEMPT_CODE = "vatReasonExemptCode";
  private String vatReasonExemptCode;

  public static final String JSON_PROPERTY_EXTRA_DATA = "extraData";
  private List<SpecificData> extraData;

  public Repartitionbyrate() { 
  }

  public Repartitionbyrate id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * id of the object
   * @return id
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(Long id) {
    this.id = id;
  }


  public Repartitionbyrate invoice(CustomerInvoiceDataLink invoice) {
    this.invoice = invoice;
    return this;
  }

   /**
   * Get invoice
   * @return invoice
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INVOICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerInvoiceDataLink getInvoice() {
    return invoice;
  }


  @JsonProperty(JSON_PROPERTY_INVOICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInvoice(CustomerInvoiceDataLink invoice) {
    this.invoice = invoice;
  }


  public Repartitionbyrate vat(VatDataLink vat) {
    this.vat = vat;
    return this;
  }

   /**
   * Get vat
   * @return vat
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VatDataLink getVat() {
    return vat;
  }


  @JsonProperty(JSON_PROPERTY_VAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVat(VatDataLink vat) {
    this.vat = vat;
  }


  public Repartitionbyrate vatBase(Double vatBase) {
    this.vatBase = vatBase;
    return this;
  }

   /**
   * VAT base
   * @return vatBase
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_BASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getVatBase() {
    return vatBase;
  }


  @JsonProperty(JSON_PROPERTY_VAT_BASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVatBase(Double vatBase) {
    this.vatBase = vatBase;
  }


  public Repartitionbyrate totalVat(Double totalVat) {
    this.totalVat = totalVat;
    return this;
  }

   /**
   * VAT total
   * @return totalVat
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_VAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTotalVat() {
    return totalVat;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_VAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalVat(Double totalVat) {
    this.totalVat = totalVat;
  }


  public Repartitionbyrate vatRate(Double vatRate) {
    this.vatRate = vatRate;
    return this;
  }

   /**
   * VAT rate
   * @return vatRate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getVatRate() {
    return vatRate;
  }


  @JsonProperty(JSON_PROPERTY_VAT_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVatRate(Double vatRate) {
    this.vatRate = vatRate;
  }


  public Repartitionbyrate vat2Base(Double vat2Base) {
    this.vat2Base = vat2Base;
    return this;
  }

   /**
   * VAT base 2
   * @return vat2Base
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT2_BASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getVat2Base() {
    return vat2Base;
  }


  @JsonProperty(JSON_PROPERTY_VAT2_BASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVat2Base(Double vat2Base) {
    this.vat2Base = vat2Base;
  }


  public Repartitionbyrate totalVat2(Double totalVat2) {
    this.totalVat2 = totalVat2;
    return this;
  }

   /**
   * VAT total 2
   * @return totalVat2
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_VAT2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTotalVat2() {
    return totalVat2;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_VAT2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalVat2(Double totalVat2) {
    this.totalVat2 = totalVat2;
  }


  public Repartitionbyrate vat2Rate(Double vat2Rate) {
    this.vat2Rate = vat2Rate;
    return this;
  }

   /**
   * VAT rate
   * @return vat2Rate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT2_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getVat2Rate() {
    return vat2Rate;
  }


  @JsonProperty(JSON_PROPERTY_VAT2_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVat2Rate(Double vat2Rate) {
    this.vat2Rate = vat2Rate;
  }


  public Repartitionbyrate vatCodeType(String vatCodeType) {
    this.vatCodeType = vatCodeType;
    return this;
  }

   /**
   * VAT type code
   * @return vatCodeType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_CODE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVatCodeType() {
    return vatCodeType;
  }


  @JsonProperty(JSON_PROPERTY_VAT_CODE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVatCodeType(String vatCodeType) {
    this.vatCodeType = vatCodeType;
  }


  public Repartitionbyrate vatTypeLabel(String vatTypeLabel) {
    this.vatTypeLabel = vatTypeLabel;
    return this;
  }

   /**
   * VAT type label
   * @return vatTypeLabel
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_TYPE_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVatTypeLabel() {
    return vatTypeLabel;
  }


  @JsonProperty(JSON_PROPERTY_VAT_TYPE_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVatTypeLabel(String vatTypeLabel) {
    this.vatTypeLabel = vatTypeLabel;
  }


  public Repartitionbyrate vatCodeTypeIds(String vatCodeTypeIds) {
    this.vatCodeTypeIds = vatCodeTypeIds;
    return this;
  }

   /**
   * VAT type Schema Id
   * @return vatCodeTypeIds
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_CODE_TYPE_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVatCodeTypeIds() {
    return vatCodeTypeIds;
  }


  @JsonProperty(JSON_PROPERTY_VAT_CODE_TYPE_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVatCodeTypeIds(String vatCodeTypeIds) {
    this.vatCodeTypeIds = vatCodeTypeIds;
  }


  public Repartitionbyrate vatReasonExempt(String vatReasonExempt) {
    this.vatReasonExempt = vatReasonExempt;
    return this;
  }

   /**
   * Reason for VAT exemption
   * @return vatReasonExempt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_REASON_EXEMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVatReasonExempt() {
    return vatReasonExempt;
  }


  @JsonProperty(JSON_PROPERTY_VAT_REASON_EXEMPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVatReasonExempt(String vatReasonExempt) {
    this.vatReasonExempt = vatReasonExempt;
  }


  public Repartitionbyrate vatReasonExemptCode(String vatReasonExemptCode) {
    this.vatReasonExemptCode = vatReasonExemptCode;
    return this;
  }

   /**
   * Code of the reason for VAT exemption
   * @return vatReasonExemptCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_REASON_EXEMPT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVatReasonExemptCode() {
    return vatReasonExemptCode;
  }


  @JsonProperty(JSON_PROPERTY_VAT_REASON_EXEMPT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVatReasonExemptCode(String vatReasonExemptCode) {
    this.vatReasonExemptCode = vatReasonExemptCode;
  }


  public Repartitionbyrate extraData(List<SpecificData> extraData) {
    this.extraData = extraData;
    return this;
  }

  public Repartitionbyrate addExtraDataItem(SpecificData extraDataItem) {
    if (this.extraData == null) {
      this.extraData = new ArrayList<>();
    }
    this.extraData.add(extraDataItem);
    return this;
  }

   /**
   * Extra data of the repartition by rate. For more information, see Extra data section
   * @return extraData
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTRA_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SpecificData> getExtraData() {
    return extraData;
  }


  @JsonProperty(JSON_PROPERTY_EXTRA_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtraData(List<SpecificData> extraData) {
    this.extraData = extraData;
  }


  /**
   * Return true if this repartitionbyrate object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Repartitionbyrate repartitionbyrate = (Repartitionbyrate) o;
    return Objects.equals(this.id, repartitionbyrate.id) &&
        Objects.equals(this.invoice, repartitionbyrate.invoice) &&
        Objects.equals(this.vat, repartitionbyrate.vat) &&
        Objects.equals(this.vatBase, repartitionbyrate.vatBase) &&
        Objects.equals(this.totalVat, repartitionbyrate.totalVat) &&
        Objects.equals(this.vatRate, repartitionbyrate.vatRate) &&
        Objects.equals(this.vat2Base, repartitionbyrate.vat2Base) &&
        Objects.equals(this.totalVat2, repartitionbyrate.totalVat2) &&
        Objects.equals(this.vat2Rate, repartitionbyrate.vat2Rate) &&
        Objects.equals(this.vatCodeType, repartitionbyrate.vatCodeType) &&
        Objects.equals(this.vatTypeLabel, repartitionbyrate.vatTypeLabel) &&
        Objects.equals(this.vatCodeTypeIds, repartitionbyrate.vatCodeTypeIds) &&
        Objects.equals(this.vatReasonExempt, repartitionbyrate.vatReasonExempt) &&
        Objects.equals(this.vatReasonExemptCode, repartitionbyrate.vatReasonExemptCode) &&
        Objects.equals(this.extraData, repartitionbyrate.extraData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, invoice, vat, vatBase, totalVat, vatRate, vat2Base, totalVat2, vat2Rate, vatCodeType, vatTypeLabel, vatCodeTypeIds, vatReasonExempt, vatReasonExemptCode, extraData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Repartitionbyrate {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    invoice: ").append(toIndentedString(invoice)).append("\n");
    sb.append("    vat: ").append(toIndentedString(vat)).append("\n");
    sb.append("    vatBase: ").append(toIndentedString(vatBase)).append("\n");
    sb.append("    totalVat: ").append(toIndentedString(totalVat)).append("\n");
    sb.append("    vatRate: ").append(toIndentedString(vatRate)).append("\n");
    sb.append("    vat2Base: ").append(toIndentedString(vat2Base)).append("\n");
    sb.append("    totalVat2: ").append(toIndentedString(totalVat2)).append("\n");
    sb.append("    vat2Rate: ").append(toIndentedString(vat2Rate)).append("\n");
    sb.append("    vatCodeType: ").append(toIndentedString(vatCodeType)).append("\n");
    sb.append("    vatTypeLabel: ").append(toIndentedString(vatTypeLabel)).append("\n");
    sb.append("    vatCodeTypeIds: ").append(toIndentedString(vatCodeTypeIds)).append("\n");
    sb.append("    vatReasonExempt: ").append(toIndentedString(vatReasonExempt)).append("\n");
    sb.append("    vatReasonExemptCode: ").append(toIndentedString(vatReasonExemptCode)).append("\n");
    sb.append("    extraData: ").append(toIndentedString(extraData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

