/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.everwin.sx.client.model.CompanyDataLink;
import fr.everwin.sx.client.model.ContactResponsibilityDataLink;
import fr.everwin.sx.client.model.DataLink;
import fr.everwin.sx.client.model.EmployeeDataLink;
import fr.everwin.sx.client.model.EquipmentDataLink;
import fr.everwin.sx.client.model.LeadDataLink;
import fr.everwin.sx.client.model.OpportunityDataLink;
import fr.everwin.sx.client.model.SpecificData;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import fr.everwin.sx.client.JSON;


/**
 * SalesAction
 */
@JsonPropertyOrder({
  SalesAction.JSON_PROPERTY_ID,
  SalesAction.JSON_PROPERTY_TYPE,
  SalesAction.JSON_PROPERTY_DESCRIPTION,
  SalesAction.JSON_PROPERTY_MAIN_PLAYER,
  SalesAction.JSON_PROPERTY_SECONDARY_PLAYERS,
  SalesAction.JSON_PROPERTY_COMPANY,
  SalesAction.JSON_PROPERTY_MAIN_CONTACT,
  SalesAction.JSON_PROPERTY_SECONDARY_CONTACTS,
  SalesAction.JSON_PROPERTY_OPPORTUNITY,
  SalesAction.JSON_PROPERTY_START_DATE,
  SalesAction.JSON_PROPERTY_PLACE,
  SalesAction.JSON_PROPERTY_DURATION,
  SalesAction.JSON_PROPERTY_END_DATE,
  SalesAction.JSON_PROPERTY_PRIORITY,
  SalesAction.JSON_PROPERTY_MARKETING_OPERATION,
  SalesAction.JSON_PROPERTY_STATUS,
  SalesAction.JSON_PROPERTY_COMPLETION_DATE,
  SalesAction.JSON_PROPERTY_ANSWER,
  SalesAction.JSON_PROPERTY_SALES_STEP,
  SalesAction.JSON_PROPERTY_INTRODUCED_COLLABORATOR,
  SalesAction.JSON_PROPERTY_IS_PRIVATE,
  SalesAction.JSON_PROPERTY_EQUIPMENTS,
  SalesAction.JSON_PROPERTY_MARKETING_CAMPAIGN,
  SalesAction.JSON_PROPERTY_LEAD,
  SalesAction.JSON_PROPERTY_UPDATED_BY,
  SalesAction.JSON_PROPERTY_UPDATED_ON_TIME,
  SalesAction.JSON_PROPERTY_CREATED_ON_TIME,
  SalesAction.JSON_PROPERTY_EXTRA_DATA
})
@JsonTypeName("salesAction")
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-05-22T08:24:46.022483900+02:00[Europe/Paris]")
public class SalesAction {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_TYPE = "type";
  private Integer type;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_MAIN_PLAYER = "mainPlayer";
  private EmployeeDataLink mainPlayer;

  public static final String JSON_PROPERTY_SECONDARY_PLAYERS = "secondaryPlayers";
  private List<EmployeeDataLink> secondaryPlayers;

  public static final String JSON_PROPERTY_COMPANY = "company";
  private CompanyDataLink company;

  public static final String JSON_PROPERTY_MAIN_CONTACT = "mainContact";
  private ContactResponsibilityDataLink mainContact;

  public static final String JSON_PROPERTY_SECONDARY_CONTACTS = "secondaryContacts";
  private List<ContactResponsibilityDataLink> secondaryContacts;

  public static final String JSON_PROPERTY_OPPORTUNITY = "opportunity";
  private OpportunityDataLink opportunity;

  public static final String JSON_PROPERTY_START_DATE = "startDate";
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "CET")
  private java.time.LocalDateTime startDate;

  public static final String JSON_PROPERTY_PLACE = "place";
  private String place;

  public static final String JSON_PROPERTY_DURATION = "duration";
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "CET")
  private java.time.LocalDateTime duration;

  public static final String JSON_PROPERTY_END_DATE = "endDate";
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "CET")
  private java.time.LocalDateTime endDate;

  public static final String JSON_PROPERTY_PRIORITY = "priority";
  private Integer priority;

  public static final String JSON_PROPERTY_MARKETING_OPERATION = "marketingOperation";
  private DataLink marketingOperation;

  public static final String JSON_PROPERTY_STATUS = "status";
  private Integer status;

  public static final String JSON_PROPERTY_COMPLETION_DATE = "completionDate";
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "CET")
  private java.time.LocalDateTime completionDate;

  public static final String JSON_PROPERTY_ANSWER = "answer";
  private Integer answer;

  public static final String JSON_PROPERTY_SALES_STEP = "salesStep";
  private DataLink salesStep;

  public static final String JSON_PROPERTY_INTRODUCED_COLLABORATOR = "introducedCollaborator";
  private EmployeeDataLink introducedCollaborator;

  /**
   * Indicactes if the sales action is private or not. 0 : No, 1 : Yes
   */
  public enum IsPrivateEnum {
    NUMBER_0(0),
    
    NUMBER_1(1);

    private Integer value;

    IsPrivateEnum(Integer value) {
      this.value = value;
    }

    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static IsPrivateEnum fromValue(Integer value) {
      for (IsPrivateEnum b : IsPrivateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_IS_PRIVATE = "isPrivate";
  private IsPrivateEnum isPrivate;

  public static final String JSON_PROPERTY_EQUIPMENTS = "equipments";
  private List<EquipmentDataLink> equipments;

  public static final String JSON_PROPERTY_MARKETING_CAMPAIGN = "marketingCampaign";
  private DataLink marketingCampaign;

  public static final String JSON_PROPERTY_LEAD = "lead";
  private LeadDataLink lead;

  public static final String JSON_PROPERTY_UPDATED_BY = "updatedBy";
  private String updatedBy;

  public static final String JSON_PROPERTY_UPDATED_ON_TIME = "updatedOnTime";
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "CET")
  private java.time.LocalDateTime updatedOnTime;

  public static final String JSON_PROPERTY_CREATED_ON_TIME = "createdOnTime";
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "CET")
  private java.time.LocalDateTime createdOnTime;

  public static final String JSON_PROPERTY_EXTRA_DATA = "extraData";
  private List<SpecificData> extraData;

  public SalesAction() { 
  }

  @JsonCreator
  public SalesAction(
    @JsonProperty(JSON_PROPERTY_UPDATED_BY) String updatedBy, 
    @JsonProperty(JSON_PROPERTY_UPDATED_ON_TIME) java.time.LocalDateTime updatedOnTime, 
    @JsonProperty(JSON_PROPERTY_CREATED_ON_TIME) java.time.LocalDateTime createdOnTime
  ) {
    this();
    this.updatedBy = updatedBy;
    this.updatedOnTime = updatedOnTime;
    this.createdOnTime = createdOnTime;
  }

  public SalesAction id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * id of the object
   * @return id
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(Long id) {
    this.id = id;
  }


  public SalesAction type(Integer type) {
    this.type = type;
    return this;
  }

   /**
   * Link to the type of the sales action. For more information, see &lt;a href&#x3D;&#39;Javascript:systemInfos(\&quot;SalesActions-Types\&quot;);&#39;&gt;Sales actions Types&lt;/a&gt; in System data section
   * @return type
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(Integer type) {
    this.type = type;
  }


  public SalesAction description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the sales action
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public SalesAction mainPlayer(EmployeeDataLink mainPlayer) {
    this.mainPlayer = mainPlayer;
    return this;
  }

   /**
   * Get mainPlayer
   * @return mainPlayer
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MAIN_PLAYER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EmployeeDataLink getMainPlayer() {
    return mainPlayer;
  }


  @JsonProperty(JSON_PROPERTY_MAIN_PLAYER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMainPlayer(EmployeeDataLink mainPlayer) {
    this.mainPlayer = mainPlayer;
  }


  public SalesAction secondaryPlayers(List<EmployeeDataLink> secondaryPlayers) {
    this.secondaryPlayers = secondaryPlayers;
    return this;
  }

  public SalesAction addSecondaryPlayersItem(EmployeeDataLink secondaryPlayersItem) {
    if (this.secondaryPlayers == null) {
      this.secondaryPlayers = new ArrayList<>();
    }
    this.secondaryPlayers.add(secondaryPlayersItem);
    return this;
  }

   /**
   * Multiple link to secondary players. For more informations see the /employees resource
   * @return secondaryPlayers
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECONDARY_PLAYERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<EmployeeDataLink> getSecondaryPlayers() {
    return secondaryPlayers;
  }


  @JsonProperty(JSON_PROPERTY_SECONDARY_PLAYERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecondaryPlayers(List<EmployeeDataLink> secondaryPlayers) {
    this.secondaryPlayers = secondaryPlayers;
  }


  public SalesAction company(CompanyDataLink company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CompanyDataLink getCompany() {
    return company;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompany(CompanyDataLink company) {
    this.company = company;
  }


  public SalesAction mainContact(ContactResponsibilityDataLink mainContact) {
    this.mainContact = mainContact;
    return this;
  }

   /**
   * Get mainContact
   * @return mainContact
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAIN_CONTACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ContactResponsibilityDataLink getMainContact() {
    return mainContact;
  }


  @JsonProperty(JSON_PROPERTY_MAIN_CONTACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMainContact(ContactResponsibilityDataLink mainContact) {
    this.mainContact = mainContact;
  }


  public SalesAction secondaryContacts(List<ContactResponsibilityDataLink> secondaryContacts) {
    this.secondaryContacts = secondaryContacts;
    return this;
  }

  public SalesAction addSecondaryContactsItem(ContactResponsibilityDataLink secondaryContactsItem) {
    if (this.secondaryContacts == null) {
      this.secondaryContacts = new ArrayList<>();
    }
    this.secondaryContacts.add(secondaryContactsItem);
    return this;
  }

   /**
   * Multiple link to contact responsabilities. For more informations see the /contact-responsabilities resource
   * @return secondaryContacts
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECONDARY_CONTACTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ContactResponsibilityDataLink> getSecondaryContacts() {
    return secondaryContacts;
  }


  @JsonProperty(JSON_PROPERTY_SECONDARY_CONTACTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecondaryContacts(List<ContactResponsibilityDataLink> secondaryContacts) {
    this.secondaryContacts = secondaryContacts;
  }


  public SalesAction opportunity(OpportunityDataLink opportunity) {
    this.opportunity = opportunity;
    return this;
  }

   /**
   * Get opportunity
   * @return opportunity
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPPORTUNITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OpportunityDataLink getOpportunity() {
    return opportunity;
  }


  @JsonProperty(JSON_PROPERTY_OPPORTUNITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpportunity(OpportunityDataLink opportunity) {
    this.opportunity = opportunity;
  }


  public SalesAction startDate(java.time.LocalDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Start date of the sales action
   * @return startDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.LocalDateTime getStartDate() {
    return startDate;
  }


  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDate(java.time.LocalDateTime startDate) {
    this.startDate = startDate;
  }


  public SalesAction place(String place) {
    this.place = place;
    return this;
  }

   /**
   * Place of the sales action
   * @return place
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPlace() {
    return place;
  }


  @JsonProperty(JSON_PROPERTY_PLACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlace(String place) {
    this.place = place;
  }


  public SalesAction duration(java.time.LocalDateTime duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Duration of the sales action
   * @return duration
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.LocalDateTime getDuration() {
    return duration;
  }


  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(java.time.LocalDateTime duration) {
    this.duration = duration;
  }


  public SalesAction endDate(java.time.LocalDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * End date of the sales action
   * @return endDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.LocalDateTime getEndDate() {
    return endDate;
  }


  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDate(java.time.LocalDateTime endDate) {
    this.endDate = endDate;
  }


  public SalesAction priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Link to the priority of the sales action. For more information, see &lt;a href&#x3D;&#39;Javascript:systemInfos(\&quot;SalesActions-Priorities\&quot;);&#39;&gt;Sales actions Priorities&lt;/a&gt; in System data section
   * @return priority
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPriority() {
    return priority;
  }


  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriority(Integer priority) {
    this.priority = priority;
  }


  public SalesAction marketingOperation(DataLink marketingOperation) {
    this.marketingOperation = marketingOperation;
    return this;
  }

   /**
   * Get marketingOperation
   * @return marketingOperation
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MARKETING_OPERATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DataLink getMarketingOperation() {
    return marketingOperation;
  }


  @JsonProperty(JSON_PROPERTY_MARKETING_OPERATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketingOperation(DataLink marketingOperation) {
    this.marketingOperation = marketingOperation;
  }


  public SalesAction status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Link to the status of the sales action. For more information, see &lt;a href&#x3D;&#39;Javascript:systemInfos(\&quot;SalesActions-Status\&quot;);&#39;&gt;Sales actions Status&lt;/a&gt; in System data section
   * @return status
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(Integer status) {
    this.status = status;
  }


  public SalesAction completionDate(java.time.LocalDateTime completionDate) {
    this.completionDate = completionDate;
    return this;
  }

   /**
   * Completion date of the sales action
   * @return completionDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPLETION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.LocalDateTime getCompletionDate() {
    return completionDate;
  }


  @JsonProperty(JSON_PROPERTY_COMPLETION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompletionDate(java.time.LocalDateTime completionDate) {
    this.completionDate = completionDate;
  }


  public SalesAction answer(Integer answer) {
    this.answer = answer;
    return this;
  }

   /**
   * Link to the answer of the sales action. For more information, see &lt;a href&#x3D;&#39;Javascript:systemInfos(\&quot;SalesActions-Answers\&quot;);&#39;&gt;Sales actions Answers&lt;/a&gt; in System data section
   * @return answer
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ANSWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAnswer() {
    return answer;
  }


  @JsonProperty(JSON_PROPERTY_ANSWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnswer(Integer answer) {
    this.answer = answer;
  }


  public SalesAction salesStep(DataLink salesStep) {
    this.salesStep = salesStep;
    return this;
  }

   /**
   * Get salesStep
   * @return salesStep
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SALES_STEP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DataLink getSalesStep() {
    return salesStep;
  }


  @JsonProperty(JSON_PROPERTY_SALES_STEP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSalesStep(DataLink salesStep) {
    this.salesStep = salesStep;
  }


  public SalesAction introducedCollaborator(EmployeeDataLink introducedCollaborator) {
    this.introducedCollaborator = introducedCollaborator;
    return this;
  }

   /**
   * Get introducedCollaborator
   * @return introducedCollaborator
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTRODUCED_COLLABORATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EmployeeDataLink getIntroducedCollaborator() {
    return introducedCollaborator;
  }


  @JsonProperty(JSON_PROPERTY_INTRODUCED_COLLABORATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntroducedCollaborator(EmployeeDataLink introducedCollaborator) {
    this.introducedCollaborator = introducedCollaborator;
  }


  public SalesAction isPrivate(IsPrivateEnum isPrivate) {
    this.isPrivate = isPrivate;
    return this;
  }

   /**
   * Indicactes if the sales action is private or not. 0 : No, 1 : Yes
   * @return isPrivate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_PRIVATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public IsPrivateEnum getIsPrivate() {
    return isPrivate;
  }


  @JsonProperty(JSON_PROPERTY_IS_PRIVATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsPrivate(IsPrivateEnum isPrivate) {
    this.isPrivate = isPrivate;
  }


  public SalesAction equipments(List<EquipmentDataLink> equipments) {
    this.equipments = equipments;
    return this;
  }

  public SalesAction addEquipmentsItem(EquipmentDataLink equipmentsItem) {
    if (this.equipments == null) {
      this.equipments = new ArrayList<>();
    }
    this.equipments.add(equipmentsItem);
    return this;
  }

   /**
   * Multiple link to equipments. For more informations see the /equipments resource
   * @return equipments
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EQUIPMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<EquipmentDataLink> getEquipments() {
    return equipments;
  }


  @JsonProperty(JSON_PROPERTY_EQUIPMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEquipments(List<EquipmentDataLink> equipments) {
    this.equipments = equipments;
  }


  public SalesAction marketingCampaign(DataLink marketingCampaign) {
    this.marketingCampaign = marketingCampaign;
    return this;
  }

   /**
   * Get marketingCampaign
   * @return marketingCampaign
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MARKETING_CAMPAIGN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DataLink getMarketingCampaign() {
    return marketingCampaign;
  }


  @JsonProperty(JSON_PROPERTY_MARKETING_CAMPAIGN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketingCampaign(DataLink marketingCampaign) {
    this.marketingCampaign = marketingCampaign;
  }


  public SalesAction lead(LeadDataLink lead) {
    this.lead = lead;
    return this;
  }

   /**
   * Get lead
   * @return lead
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LeadDataLink getLead() {
    return lead;
  }


  @JsonProperty(JSON_PROPERTY_LEAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLead(LeadDataLink lead) {
    this.lead = lead;
  }


   /**
   * Login of the user doing the last update on the sales action
   * @return updatedBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdatedBy() {
    return updatedBy;
  }




   /**
   * Date &amp; time of the last update of the sales action
   * @return updatedOnTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_ON_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.LocalDateTime getUpdatedOnTime() {
    return updatedOnTime;
  }




   /**
   * Date &amp; time of creation of the sales action
   * @return createdOnTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_ON_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.LocalDateTime getCreatedOnTime() {
    return createdOnTime;
  }




  public SalesAction extraData(List<SpecificData> extraData) {
    this.extraData = extraData;
    return this;
  }

  public SalesAction addExtraDataItem(SpecificData extraDataItem) {
    if (this.extraData == null) {
      this.extraData = new ArrayList<>();
    }
    this.extraData.add(extraDataItem);
    return this;
  }

   /**
   * Extra data of the sales action. For more information, see Extra data section
   * @return extraData
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTRA_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SpecificData> getExtraData() {
    return extraData;
  }


  @JsonProperty(JSON_PROPERTY_EXTRA_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtraData(List<SpecificData> extraData) {
    this.extraData = extraData;
  }


  /**
   * Return true if this salesAction object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalesAction salesAction = (SalesAction) o;
    return Objects.equals(this.id, salesAction.id) &&
        Objects.equals(this.type, salesAction.type) &&
        Objects.equals(this.description, salesAction.description) &&
        Objects.equals(this.mainPlayer, salesAction.mainPlayer) &&
        Objects.equals(this.secondaryPlayers, salesAction.secondaryPlayers) &&
        Objects.equals(this.company, salesAction.company) &&
        Objects.equals(this.mainContact, salesAction.mainContact) &&
        Objects.equals(this.secondaryContacts, salesAction.secondaryContacts) &&
        Objects.equals(this.opportunity, salesAction.opportunity) &&
        Objects.equals(this.startDate, salesAction.startDate) &&
        Objects.equals(this.place, salesAction.place) &&
        Objects.equals(this.duration, salesAction.duration) &&
        Objects.equals(this.endDate, salesAction.endDate) &&
        Objects.equals(this.priority, salesAction.priority) &&
        Objects.equals(this.marketingOperation, salesAction.marketingOperation) &&
        Objects.equals(this.status, salesAction.status) &&
        Objects.equals(this.completionDate, salesAction.completionDate) &&
        Objects.equals(this.answer, salesAction.answer) &&
        Objects.equals(this.salesStep, salesAction.salesStep) &&
        Objects.equals(this.introducedCollaborator, salesAction.introducedCollaborator) &&
        Objects.equals(this.isPrivate, salesAction.isPrivate) &&
        Objects.equals(this.equipments, salesAction.equipments) &&
        Objects.equals(this.marketingCampaign, salesAction.marketingCampaign) &&
        Objects.equals(this.lead, salesAction.lead) &&
        Objects.equals(this.updatedBy, salesAction.updatedBy) &&
        Objects.equals(this.updatedOnTime, salesAction.updatedOnTime) &&
        Objects.equals(this.createdOnTime, salesAction.createdOnTime) &&
        Objects.equals(this.extraData, salesAction.extraData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, description, mainPlayer, secondaryPlayers, company, mainContact, secondaryContacts, opportunity, startDate, place, duration, endDate, priority, marketingOperation, status, completionDate, answer, salesStep, introducedCollaborator, isPrivate, equipments, marketingCampaign, lead, updatedBy, updatedOnTime, createdOnTime, extraData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalesAction {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    mainPlayer: ").append(toIndentedString(mainPlayer)).append("\n");
    sb.append("    secondaryPlayers: ").append(toIndentedString(secondaryPlayers)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    mainContact: ").append(toIndentedString(mainContact)).append("\n");
    sb.append("    secondaryContacts: ").append(toIndentedString(secondaryContacts)).append("\n");
    sb.append("    opportunity: ").append(toIndentedString(opportunity)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    place: ").append(toIndentedString(place)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    marketingOperation: ").append(toIndentedString(marketingOperation)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    completionDate: ").append(toIndentedString(completionDate)).append("\n");
    sb.append("    answer: ").append(toIndentedString(answer)).append("\n");
    sb.append("    salesStep: ").append(toIndentedString(salesStep)).append("\n");
    sb.append("    introducedCollaborator: ").append(toIndentedString(introducedCollaborator)).append("\n");
    sb.append("    isPrivate: ").append(toIndentedString(isPrivate)).append("\n");
    sb.append("    equipments: ").append(toIndentedString(equipments)).append("\n");
    sb.append("    marketingCampaign: ").append(toIndentedString(marketingCampaign)).append("\n");
    sb.append("    lead: ").append(toIndentedString(lead)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    updatedOnTime: ").append(toIndentedString(updatedOnTime)).append("\n");
    sb.append("    createdOnTime: ").append(toIndentedString(createdOnTime)).append("\n");
    sb.append("    extraData: ").append(toIndentedString(extraData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

