/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * SupplierInvoice
 */
@JsonPropertyOrder({
  SupplierInvoice.JSON_PROPERTY_ID,
  SupplierInvoice.JSON_PROPERTY_VALIDATION_STEP,
  SupplierInvoice.JSON_PROPERTY_CODE,
  SupplierInvoice.JSON_PROPERTY_SUPPLIER,
  SupplierInvoice.JSON_PROPERTY_CONTACT,
  SupplierInvoice.JSON_PROPERTY_ENTITY,
  SupplierInvoice.JSON_PROPERTY_FINANCIAL_ENTITY,
  SupplierInvoice.JSON_PROPERTY_LAST_VALIDATOR,
  SupplierInvoice.JSON_PROPERTY_PAYMENT_TERMS,
  SupplierInvoice.JSON_PROPERTY_SUPPLIER_ACCOUNT,
  SupplierInvoice.JSON_PROPERTY_DATE,
  SupplierInvoice.JSON_PROPERTY_DUE_DATE,
  SupplierInvoice.JSON_PROPERTY_REFERENCE,
  SupplierInvoice.JSON_PROPERTY_SETTLEMENT_STATUS,
  SupplierInvoice.JSON_PROPERTY_SETTLEMENT_COMENTS,
  SupplierInvoice.JSON_PROPERTY_FISCAL_POSITION,
  SupplierInvoice.JSON_PROPERTY_CURRENCY,
  SupplierInvoice.JSON_PROPERTY_TOTAL_WITHOUT_VAT,
  SupplierInvoice.JSON_PROPERTY_TOTAL_INCLUDING_VAT,
  SupplierInvoice.JSON_PROPERTY_TOTAL_VAT,
  SupplierInvoice.JSON_PROPERTY_TOTAL_TO_BE_CHARGED,
  SupplierInvoice.JSON_PROPERTY_EXTRA_DATA
})
@JsonTypeName("supplierInvoice")
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-10-06T08:58:20.555636300+02:00[Europe/Paris]")
public class SupplierInvoice {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_VALIDATION_STEP = "validationStep";
  private String validationStep;

  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_SUPPLIER = "supplier";
  private CompanyDataLink supplier;

  public static final String JSON_PROPERTY_CONTACT = "contact";
  private ContactResponsibilityDataLink contact;

  public static final String JSON_PROPERTY_ENTITY = "entity";
  private EntityDataLink entity;

  public static final String JSON_PROPERTY_FINANCIAL_ENTITY = "financialEntity";
  private EntityDataLink financialEntity;

  public static final String JSON_PROPERTY_LAST_VALIDATOR = "lastValidator";
  private EmployeeDataLink lastValidator;

  public static final String JSON_PROPERTY_PAYMENT_TERMS = "paymentTerms";
  private DataLink paymentTerms;

  public static final String JSON_PROPERTY_SUPPLIER_ACCOUNT = "supplierAccount";
  private CompanyAccountDataLink supplierAccount;

  public static final String JSON_PROPERTY_DATE = "date";
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "CET")
  private java.time.LocalDateTime date;

  public static final String JSON_PROPERTY_DUE_DATE = "dueDate";
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss", timezone = "CET")
  private java.time.LocalDateTime dueDate;

  public static final String JSON_PROPERTY_REFERENCE = "reference";
  private String reference;

  public static final String JSON_PROPERTY_SETTLEMENT_STATUS = "settlementStatus";
  private Integer settlementStatus;

  public static final String JSON_PROPERTY_SETTLEMENT_COMENTS = "settlementComents";
  private String settlementComents;

  public static final String JSON_PROPERTY_FISCAL_POSITION = "fiscalPosition";
  private DataLink fiscalPosition;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private String currency;

  public static final String JSON_PROPERTY_TOTAL_WITHOUT_VAT = "totalWithoutVat";
  private Double totalWithoutVat;

  public static final String JSON_PROPERTY_TOTAL_INCLUDING_VAT = "totalIncludingVat";
  private Double totalIncludingVat;

  public static final String JSON_PROPERTY_TOTAL_VAT = "totalVat";
  private Double totalVat;

  public static final String JSON_PROPERTY_TOTAL_TO_BE_CHARGED = "totalToBeCharged";
  private Double totalToBeCharged;

  public static final String JSON_PROPERTY_EXTRA_DATA = "extraData";
  private List<SpecificData> extraData;

  public SupplierInvoice() { 
  }

  @JsonCreator
  public SupplierInvoice(
    @JsonProperty(JSON_PROPERTY_TOTAL_WITHOUT_VAT) Double totalWithoutVat, 
    @JsonProperty(JSON_PROPERTY_TOTAL_INCLUDING_VAT) Double totalIncludingVat, 
    @JsonProperty(JSON_PROPERTY_TOTAL_VAT) Double totalVat, 
    @JsonProperty(JSON_PROPERTY_TOTAL_TO_BE_CHARGED) Double totalToBeCharged
  ) {
    this();
    this.totalWithoutVat = totalWithoutVat;
    this.totalIncludingVat = totalIncludingVat;
    this.totalVat = totalVat;
    this.totalToBeCharged = totalToBeCharged;
  }

  public SupplierInvoice id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * id of the object
   * @return id
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(Long id) {
    this.id = id;
  }


  public SupplierInvoice validationStep(String validationStep) {
    this.validationStep = validationStep;
    return this;
  }

   /**
   * Validation step of the element
   * @return validationStep
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALIDATION_STEP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getValidationStep() {
    return validationStep;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATION_STEP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValidationStep(String validationStep) {
    this.validationStep = validationStep;
  }


  public SupplierInvoice code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Code of the supplier invoice
   * @return code
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(String code) {
    this.code = code;
  }


  public SupplierInvoice supplier(CompanyDataLink supplier) {
    this.supplier = supplier;
    return this;
  }

   /**
   * Get supplier
   * @return supplier
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUPPLIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CompanyDataLink getSupplier() {
    return supplier;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSupplier(CompanyDataLink supplier) {
    this.supplier = supplier;
  }


  public SupplierInvoice contact(ContactResponsibilityDataLink contact) {
    this.contact = contact;
    return this;
  }

   /**
   * Get contact
   * @return contact
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ContactResponsibilityDataLink getContact() {
    return contact;
  }


  @JsonProperty(JSON_PROPERTY_CONTACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContact(ContactResponsibilityDataLink contact) {
    this.contact = contact;
  }


  public SupplierInvoice entity(EntityDataLink entity) {
    this.entity = entity;
    return this;
  }

   /**
   * Get entity
   * @return entity
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ENTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EntityDataLink getEntity() {
    return entity;
  }


  @JsonProperty(JSON_PROPERTY_ENTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntity(EntityDataLink entity) {
    this.entity = entity;
  }


  public SupplierInvoice financialEntity(EntityDataLink financialEntity) {
    this.financialEntity = financialEntity;
    return this;
  }

   /**
   * Get financialEntity
   * @return financialEntity
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINANCIAL_ENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EntityDataLink getFinancialEntity() {
    return financialEntity;
  }


  @JsonProperty(JSON_PROPERTY_FINANCIAL_ENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinancialEntity(EntityDataLink financialEntity) {
    this.financialEntity = financialEntity;
  }


  public SupplierInvoice lastValidator(EmployeeDataLink lastValidator) {
    this.lastValidator = lastValidator;
    return this;
  }

   /**
   * Get lastValidator
   * @return lastValidator
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_VALIDATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EmployeeDataLink getLastValidator() {
    return lastValidator;
  }


  @JsonProperty(JSON_PROPERTY_LAST_VALIDATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastValidator(EmployeeDataLink lastValidator) {
    this.lastValidator = lastValidator;
  }


  public SupplierInvoice paymentTerms(DataLink paymentTerms) {
    this.paymentTerms = paymentTerms;
    return this;
  }

   /**
   * Get paymentTerms
   * @return paymentTerms
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_TERMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DataLink getPaymentTerms() {
    return paymentTerms;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_TERMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentTerms(DataLink paymentTerms) {
    this.paymentTerms = paymentTerms;
  }


  public SupplierInvoice supplierAccount(CompanyAccountDataLink supplierAccount) {
    this.supplierAccount = supplierAccount;
    return this;
  }

   /**
   * Get supplierAccount
   * @return supplierAccount
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPLIER_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CompanyAccountDataLink getSupplierAccount() {
    return supplierAccount;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLIER_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupplierAccount(CompanyAccountDataLink supplierAccount) {
    this.supplierAccount = supplierAccount;
  }


  public SupplierInvoice date(java.time.LocalDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Date of the supplier invoice
   * @return date
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public java.time.LocalDateTime getDate() {
    return date;
  }


  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDate(java.time.LocalDateTime date) {
    this.date = date;
  }


  public SupplierInvoice dueDate(java.time.LocalDateTime dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Due date of the supplier invoice
   * @return dueDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DUE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.LocalDateTime getDueDate() {
    return dueDate;
  }


  @JsonProperty(JSON_PROPERTY_DUE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDueDate(java.time.LocalDateTime dueDate) {
    this.dueDate = dueDate;
  }


  public SupplierInvoice reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Supplier reference of the invoice
   * @return reference
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReference() {
    return reference;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReference(String reference) {
    this.reference = reference;
  }


  public SupplierInvoice settlementStatus(Integer settlementStatus) {
    this.settlementStatus = settlementStatus;
    return this;
  }

   /**
   * Settlement status of the invoice
   * @return settlementStatus
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SETTLEMENT_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSettlementStatus() {
    return settlementStatus;
  }


  @JsonProperty(JSON_PROPERTY_SETTLEMENT_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSettlementStatus(Integer settlementStatus) {
    this.settlementStatus = settlementStatus;
  }


  public SupplierInvoice settlementComents(String settlementComents) {
    this.settlementComents = settlementComents;
    return this;
  }

   /**
   * Settlement comments of the invoice
   * @return settlementComents
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SETTLEMENT_COMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSettlementComents() {
    return settlementComents;
  }


  @JsonProperty(JSON_PROPERTY_SETTLEMENT_COMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSettlementComents(String settlementComents) {
    this.settlementComents = settlementComents;
  }


  public SupplierInvoice fiscalPosition(DataLink fiscalPosition) {
    this.fiscalPosition = fiscalPosition;
    return this;
  }

   /**
   * Get fiscalPosition
   * @return fiscalPosition
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FISCAL_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DataLink getFiscalPosition() {
    return fiscalPosition;
  }


  @JsonProperty(JSON_PROPERTY_FISCAL_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFiscalPosition(DataLink fiscalPosition) {
    this.fiscalPosition = fiscalPosition;
  }


  public SupplierInvoice currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency of the supplier invoice (ISO code)
   * @return currency
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(String currency) {
    this.currency = currency;
  }


   /**
   * Total without vat of the supplier invoice
   * @return totalWithoutVat
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_WITHOUT_VAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTotalWithoutVat() {
    return totalWithoutVat;
  }




   /**
   * Total including Vat of the supplier invoice
   * @return totalIncludingVat
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_INCLUDING_VAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTotalIncludingVat() {
    return totalIncludingVat;
  }




   /**
   * Total Vat of the supplier invoice
   * @return totalVat
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_VAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTotalVat() {
    return totalVat;
  }




   /**
   * Total to be recharged of the supplier invoice
   * @return totalToBeCharged
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_TO_BE_CHARGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTotalToBeCharged() {
    return totalToBeCharged;
  }




  public SupplierInvoice extraData(List<SpecificData> extraData) {
    this.extraData = extraData;
    return this;
  }

  public SupplierInvoice addExtraDataItem(SpecificData extraDataItem) {
    if (this.extraData == null) {
      this.extraData = new ArrayList<>();
    }
    this.extraData.add(extraDataItem);
    return this;
  }

   /**
   * Extra data of the supplier invoice. For more information, see Extra data section
   * @return extraData
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTRA_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SpecificData> getExtraData() {
    return extraData;
  }


  @JsonProperty(JSON_PROPERTY_EXTRA_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtraData(List<SpecificData> extraData) {
    this.extraData = extraData;
  }


  /**
   * Return true if this supplierInvoice object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupplierInvoice supplierInvoice = (SupplierInvoice) o;
    return Objects.equals(this.id, supplierInvoice.id) &&
        Objects.equals(this.validationStep, supplierInvoice.validationStep) &&
        Objects.equals(this.code, supplierInvoice.code) &&
        Objects.equals(this.supplier, supplierInvoice.supplier) &&
        Objects.equals(this.contact, supplierInvoice.contact) &&
        Objects.equals(this.entity, supplierInvoice.entity) &&
        Objects.equals(this.financialEntity, supplierInvoice.financialEntity) &&
        Objects.equals(this.lastValidator, supplierInvoice.lastValidator) &&
        Objects.equals(this.paymentTerms, supplierInvoice.paymentTerms) &&
        Objects.equals(this.supplierAccount, supplierInvoice.supplierAccount) &&
        Objects.equals(this.date, supplierInvoice.date) &&
        Objects.equals(this.dueDate, supplierInvoice.dueDate) &&
        Objects.equals(this.reference, supplierInvoice.reference) &&
        Objects.equals(this.settlementStatus, supplierInvoice.settlementStatus) &&
        Objects.equals(this.settlementComents, supplierInvoice.settlementComents) &&
        Objects.equals(this.fiscalPosition, supplierInvoice.fiscalPosition) &&
        Objects.equals(this.currency, supplierInvoice.currency) &&
        Objects.equals(this.totalWithoutVat, supplierInvoice.totalWithoutVat) &&
        Objects.equals(this.totalIncludingVat, supplierInvoice.totalIncludingVat) &&
        Objects.equals(this.totalVat, supplierInvoice.totalVat) &&
        Objects.equals(this.totalToBeCharged, supplierInvoice.totalToBeCharged) &&
        Objects.equals(this.extraData, supplierInvoice.extraData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, validationStep, code, supplier, contact, entity, financialEntity, lastValidator, paymentTerms, supplierAccount, date, dueDate, reference, settlementStatus, settlementComents, fiscalPosition, currency, totalWithoutVat, totalIncludingVat, totalVat, totalToBeCharged, extraData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupplierInvoice {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    validationStep: ").append(toIndentedString(validationStep)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    supplier: ").append(toIndentedString(supplier)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
    sb.append("    financialEntity: ").append(toIndentedString(financialEntity)).append("\n");
    sb.append("    lastValidator: ").append(toIndentedString(lastValidator)).append("\n");
    sb.append("    paymentTerms: ").append(toIndentedString(paymentTerms)).append("\n");
    sb.append("    supplierAccount: ").append(toIndentedString(supplierAccount)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    settlementStatus: ").append(toIndentedString(settlementStatus)).append("\n");
    sb.append("    settlementComents: ").append(toIndentedString(settlementComents)).append("\n");
    sb.append("    fiscalPosition: ").append(toIndentedString(fiscalPosition)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    totalWithoutVat: ").append(toIndentedString(totalWithoutVat)).append("\n");
    sb.append("    totalIncludingVat: ").append(toIndentedString(totalIncludingVat)).append("\n");
    sb.append("    totalVat: ").append(toIndentedString(totalVat)).append("\n");
    sb.append("    totalToBeCharged: ").append(toIndentedString(totalToBeCharged)).append("\n");
    sb.append("    extraData: ").append(toIndentedString(extraData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

