/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * supplierreceivingnotelinelist
 */
@JsonPropertyOrder({
  SupplierReceivingNoteLineList.JSON_PROPERTY_SUPPLIERRECEIVINGNOTELINES,
  SupplierReceivingNoteLineList.JSON_PROPERTY_SELFLINK
})
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-10-06T08:58:20.555636300+02:00[Europe/Paris]")
public class SupplierReceivingNoteLineList {
  public static final String JSON_PROPERTY_SUPPLIERRECEIVINGNOTELINES = "supplierreceivingnotelines";
  private List<SupplierReceivingNoteLine> supplierreceivingnotelines;

  public static final String JSON_PROPERTY_SELFLINK = "selflink";
  private String selflink;

  public SupplierReceivingNoteLineList() { 
  }

  public SupplierReceivingNoteLineList supplierreceivingnotelines(List<SupplierReceivingNoteLine> supplierreceivingnotelines) {
    this.supplierreceivingnotelines = supplierreceivingnotelines;
    return this;
  }

  public SupplierReceivingNoteLineList addSupplierreceivingnotelinesItem(SupplierReceivingNoteLine supplierreceivingnotelinesItem) {
    if (this.supplierreceivingnotelines == null) {
      this.supplierreceivingnotelines = new ArrayList<>();
    }
    this.supplierreceivingnotelines.add(supplierreceivingnotelinesItem);
    return this;
  }

   /**
   * Get supplierreceivingnotelines
   * @return supplierreceivingnotelines
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPLIERRECEIVINGNOTELINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SupplierReceivingNoteLine> getSupplierreceivingnotelines() {
    return supplierreceivingnotelines;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLIERRECEIVINGNOTELINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupplierreceivingnotelines(List<SupplierReceivingNoteLine> supplierreceivingnotelines) {
    this.supplierreceivingnotelines = supplierreceivingnotelines;
  }


  public SupplierReceivingNoteLineList selflink(String selflink) {
    this.selflink = selflink;
    return this;
  }

   /**
   * Get selflink
   * @return selflink
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSelflink() {
    return selflink;
  }


  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelflink(String selflink) {
    this.selflink = selflink;
  }


  /**
   * Return true if this SupplierReceivingNoteLineList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupplierReceivingNoteLineList supplierReceivingNoteLineList = (SupplierReceivingNoteLineList) o;
    return Objects.equals(this.supplierreceivingnotelines, supplierReceivingNoteLineList.supplierreceivingnotelines) &&
        Objects.equals(this.selflink, supplierReceivingNoteLineList.selflink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supplierreceivingnotelines, selflink);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupplierReceivingNoteLineList {\n");
    sb.append("    supplierreceivingnotelines: ").append(toIndentedString(supplierreceivingnotelines)).append("\n");
    sb.append("    selflink: ").append(toIndentedString(selflink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

