/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * supplierinvoicelinelist
 */
@JsonPropertyOrder({
  SupplierInvoiceLineList.JSON_PROPERTY_SUPPLIERINVOICELINES,
  SupplierInvoiceLineList.JSON_PROPERTY_SELFLINK
})
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-10-06T08:58:20.555636300+02:00[Europe/Paris]")
public class SupplierInvoiceLineList {
  public static final String JSON_PROPERTY_SUPPLIERINVOICELINES = "supplierinvoicelines";
  private List<SupplierInvoiceLine> supplierinvoicelines;

  public static final String JSON_PROPERTY_SELFLINK = "selflink";
  private String selflink;

  public SupplierInvoiceLineList() { 
  }

  public SupplierInvoiceLineList supplierinvoicelines(List<SupplierInvoiceLine> supplierinvoicelines) {
    this.supplierinvoicelines = supplierinvoicelines;
    return this;
  }

  public SupplierInvoiceLineList addSupplierinvoicelinesItem(SupplierInvoiceLine supplierinvoicelinesItem) {
    if (this.supplierinvoicelines == null) {
      this.supplierinvoicelines = new ArrayList<>();
    }
    this.supplierinvoicelines.add(supplierinvoicelinesItem);
    return this;
  }

   /**
   * Get supplierinvoicelines
   * @return supplierinvoicelines
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPLIERINVOICELINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SupplierInvoiceLine> getSupplierinvoicelines() {
    return supplierinvoicelines;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLIERINVOICELINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupplierinvoicelines(List<SupplierInvoiceLine> supplierinvoicelines) {
    this.supplierinvoicelines = supplierinvoicelines;
  }


  public SupplierInvoiceLineList selflink(String selflink) {
    this.selflink = selflink;
    return this;
  }

   /**
   * Get selflink
   * @return selflink
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSelflink() {
    return selflink;
  }


  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelflink(String selflink) {
    this.selflink = selflink;
  }


  /**
   * Return true if this SupplierInvoiceLineList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupplierInvoiceLineList supplierInvoiceLineList = (SupplierInvoiceLineList) o;
    return Objects.equals(this.supplierinvoicelines, supplierInvoiceLineList.supplierinvoicelines) &&
        Objects.equals(this.selflink, supplierInvoiceLineList.selflink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supplierinvoicelines, selflink);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupplierInvoiceLineList {\n");
    sb.append("    supplierinvoicelines: ").append(toIndentedString(supplierinvoicelines)).append("\n");
    sb.append("    selflink: ").append(toIndentedString(selflink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

