/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * supplierinvoicelist
 */
@JsonPropertyOrder({
  SupplierInvoiceList.JSON_PROPERTY_SUPPLIERINVOICES,
  SupplierInvoiceList.JSON_PROPERTY_SELFLINK
})
@jakarta.annotation.Generated(value = "fr.everwin.sx.openapi.codegen.CustomJavaClientCodegen", date = "2025-10-06T08:58:20.555636300+02:00[Europe/Paris]")
public class SupplierInvoiceList {
  public static final String JSON_PROPERTY_SUPPLIERINVOICES = "supplierinvoices";
  private List<SupplierInvoice> supplierinvoices;

  public static final String JSON_PROPERTY_SELFLINK = "selflink";
  private String selflink;

  public SupplierInvoiceList() { 
  }

  public SupplierInvoiceList supplierinvoices(List<SupplierInvoice> supplierinvoices) {
    this.supplierinvoices = supplierinvoices;
    return this;
  }

  public SupplierInvoiceList addSupplierinvoicesItem(SupplierInvoice supplierinvoicesItem) {
    if (this.supplierinvoices == null) {
      this.supplierinvoices = new ArrayList<>();
    }
    this.supplierinvoices.add(supplierinvoicesItem);
    return this;
  }

   /**
   * Get supplierinvoices
   * @return supplierinvoices
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPLIERINVOICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SupplierInvoice> getSupplierinvoices() {
    return supplierinvoices;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLIERINVOICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupplierinvoices(List<SupplierInvoice> supplierinvoices) {
    this.supplierinvoices = supplierinvoices;
  }


  public SupplierInvoiceList selflink(String selflink) {
    this.selflink = selflink;
    return this;
  }

   /**
   * Get selflink
   * @return selflink
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSelflink() {
    return selflink;
  }


  @JsonProperty(JSON_PROPERTY_SELFLINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelflink(String selflink) {
    this.selflink = selflink;
  }


  /**
   * Return true if this SupplierInvoiceList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupplierInvoiceList supplierInvoiceList = (SupplierInvoiceList) o;
    return Objects.equals(this.supplierinvoices, supplierInvoiceList.supplierinvoices) &&
        Objects.equals(this.selflink, supplierInvoiceList.selflink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supplierinvoices, selflink);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupplierInvoiceList {\n");
    sb.append("    supplierinvoices: ").append(toIndentedString(supplierinvoices)).append("\n");
    sb.append("    selflink: ").append(toIndentedString(selflink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

