/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.api;

import fr.everwin.sx.client.ApiException;
import org.junit.jupiter.api.Test;

/**
 * API tests for CompanyStaffSizesApi
 */
public class CompanyStaffSizesApiTest {

    private final CompanyStaffSizesApi api = new CompanyStaffSizesApi();

    /**
     * Create a staff size
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createStaffSizeTest() throws ApiException {
        //StaffSize staffSize = null;
        //StaffSize response = api.createStaffSize(staffSize);
        // TODO: test validations
    }

    /**
     * Delete a staff size
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteStaffSizeTest() throws ApiException {
        //Long id = null;
        //api.deleteStaffSize(id);
        // TODO: test validations
    }

    /**
     * Get a staff size by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getStaffSizeByIdTest() throws ApiException {
        //Long id = null;
        //String fields = null;
        //StaffSize response = api.getStaffSizeById(id, fields);
        // TODO: test validations
    }

    /**
     * Test company staffs sizes service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pingStaffSizeTest() throws ApiException {
        //String response = api.pingStaffSize();
        // TODO: test validations
    }

    /**
     * Get a collection of staffs sizes
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryStaffSizeTest() throws ApiException {
        //String filter = null;
        //String sort = null;
        //Integer offset = null;
        //Integer limit = null;
        //String fields = null;
        //StaffSizeList response = api.queryStaffSize(filter, sort, offset, limit, fields);
        // TODO: test validations
    }

    /**
     * Partial update of a staff size
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePartialStaffSizeTest() throws ApiException {
        //Long id = null;
        //StaffSize staffSize = null;
        //api.updatePartialStaffSize(id, staffSize);
        // TODO: test validations
    }

    /**
     * Full update of a staff size. If staff size doesn&#39;t exist, it&#39;s created.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateStaffSizeTest() throws ApiException {
        //Long id = null;
        //StaffSize staffSize = null;
        //api.updateStaffSize(id, staffSize);
        // TODO: test validations
    }

}
