/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.api;

import fr.everwin.sx.client.ApiException;
import org.junit.jupiter.api.Test;

/**
 * API tests for CustomerPaymentLinesApi
 */
public class CustomerPaymentLinesApiTest {

    private final CustomerPaymentLinesApi api = new CustomerPaymentLinesApi();

    /**
     * Create a customer payment line
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createCustomerPaymentLineTest() throws ApiException {
        //CustomerPaymentLine customerPaymentLine = null;
        //CustomerPaymentLine response = api.createCustomerPaymentLine(customerPaymentLine);
        // TODO: test validations
    }

    /**
     * Delete a customer payment line
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteCustomerPaymentLineTest() throws ApiException {
        //Long id = null;
        //api.deleteCustomerPaymentLine(id);
        // TODO: test validations
    }

    /**
     * Get a customer payment line by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCustomerPaymentLineByIdTest() throws ApiException {
        //Long id = null;
        //String fields = null;
        //CustomerPaymentLine response = api.getCustomerPaymentLineById(id, fields);
        // TODO: test validations
    }

    /**
     * Test Customer payment lines service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pingCustomerPaymentLineTest() throws ApiException {
        //String response = api.pingCustomerPaymentLine();
        // TODO: test validations
    }

    /**
     * Get a customer payment line collection
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryCustomerPaymentLineTest() throws ApiException {
        //String filter = null;
        //String sort = null;
        //Integer offset = null;
        //Integer limit = null;
        //String fields = null;
        //CustomerPaymentLineList response = api.queryCustomerPaymentLine(filter, sort, offset, limit, fields);
        // TODO: test validations
    }

    /**
     * Full update of a customer payment line. If customer payment line doesn&#39;t exist, it&#39;s created.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateCustomerPaymentLineTest() throws ApiException {
        //Long id = null;
        //CustomerPaymentLine customerPaymentLine = null;
        //api.updateCustomerPaymentLine(id, customerPaymentLine);
        // TODO: test validations
    }

    /**
     * Partial update of a customer payment line
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePartialCustomerPaymentLineTest() throws ApiException {
        //Long id = null;
        //CustomerPaymentLine customerPaymentLine = null;
        //api.updatePartialCustomerPaymentLine(id, customerPaymentLine);
        // TODO: test validations
    }

}
