/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.00.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.api;

import fr.everwin.sx.client.ApiException;
import org.junit.jupiter.api.Test;

/**
 * API tests for EInvoicingLinesApi
 */
public class EInvoicingLinesApiTest {

    private final EInvoicingLinesApi api = new EInvoicingLinesApi();

    /**
     * Test E-Invoicing lines service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pingEInvoicingLineTest() throws ApiException {
        //String response = api.pingEInvoicingLine();
        // TODO: test validations
    }

    /**
     * Get a collection of E-Invoicing lines
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryEInvoicingLinesTest() throws ApiException {
        //String filter = null;
        //String sort = null;
        //Integer offset = null;
        //Integer limit = null;
        //String fields = null;
        //EInvoicingLinePojoList response = api.queryEInvoicingLines(filter, sort, offset, limit, fields);
        // TODO: test validations
    }

}
