/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.api;

import fr.everwin.sx.client.ApiException;
import org.junit.jupiter.api.Test;

/**
 * API tests for PaymentTermsApi
 */
public class PaymentTermsApiTest {

    private final PaymentTermsApi api = new PaymentTermsApi();

    /**
     * Create a payment term
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createPaymentTermTest() throws ApiException {
        //PaymentTerm paymentTerm = null;
        //PaymentTerm response = api.createPaymentTerm(paymentTerm);
        // TODO: test validations
    }

    /**
     * Delete a payment term
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePaymentTermTest() throws ApiException {
        //Long id = null;
        //api.deletePaymentTerm(id);
        // TODO: test validations
    }

    /**
     * Get a payment term by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPaymentTermByIdTest() throws ApiException {
        //Long id = null;
        //String fields = null;
        //PaymentTerm response = api.getPaymentTermById(id, fields);
        // TODO: test validations
    }

    /**
     * Test payment terms service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pingPaymentTermTest() throws ApiException {
        //String response = api.pingPaymentTerm();
        // TODO: test validations
    }

    /**
     * Get a collection of payment terms
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryPaymentTermTest() throws ApiException {
        //String filter = null;
        //String sort = null;
        //Integer offset = null;
        //Integer limit = null;
        //String fields = null;
        //PaymentTermList response = api.queryPaymentTerm(filter, sort, offset, limit, fields);
        // TODO: test validations
    }

    /**
     * Partial update of a payment term
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePartialPaymentTermTest() throws ApiException {
        //Long id = null;
        //PaymentTerm paymentTerm = null;
        //api.updatePartialPaymentTerm(id, paymentTerm);
        // TODO: test validations
    }

    /**
     * Full update of a payment term. If payment term doesn&#39;t exist, it&#39;s created.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePaymentTermTest() throws ApiException {
        //Long id = null;
        //PaymentTerm paymentTerm = null;
        //api.updatePaymentTerm(id, paymentTerm);
        // TODO: test validations
    }

}
