/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.00.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.api;

import fr.everwin.sx.client.ApiException;
import org.junit.jupiter.api.Test;

/**
 * API tests for ProductsGroupsApi
 */
public class ProductsGroupsApiTest {

    private final ProductsGroupsApi api = new ProductsGroupsApi();

    /**
     * Create a product group
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createProductGroupTest() throws ApiException {
        //Group group = null;
        //Group response = api.createProductGroup(group);
        // TODO: test validations
    }

    /**
     * Delete a product group
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteProductGroupTest() throws ApiException {
        //Long id = null;
        //api.deleteProductGroup(id);
        // TODO: test validations
    }

    /**
     * Get an group by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProductGroupByIdTest() throws ApiException {
        //Long id = null;
        //String fields = null;
        //Group response = api.getProductGroupById(id, fields);
        // TODO: test validations
    }

    /**
     * Test Products groups service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pingProductGroupTest() throws ApiException {
        //String response = api.pingProductGroup();
        // TODO: test validations
    }

    /**
     * Get a collection of groups
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryProductGroupTest() throws ApiException {
        //String filter = null;
        //String sort = null;
        //Integer offset = null;
        //Integer limit = null;
        //String fields = null;
        //GroupList response = api.queryProductGroup(filter, sort, offset, limit, fields);
        // TODO: test validations
    }

    /**
     * Partial update of a product group
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePartialProductGroupTest() throws ApiException {
        //Long id = null;
        //Group group = null;
        //api.updatePartialProductGroup(id, group);
        // TODO: test validations
    }

    /**
     * Full update of a product group. If group doesn&#39;t exist, it&#39;s created.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateProductGroupTest() throws ApiException {
        //Long id = null;
        //Group group = null;
        //api.updateProductGroup(id, group);
        // TODO: test validations
    }

}
