/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.api;

import fr.everwin.sx.client.ApiException;
import org.junit.jupiter.api.Test;

/**
 * API tests for PurchaseRequestLinesApi
 */
public class PurchaseRequestLinesApiTest {

    private final PurchaseRequestLinesApi api = new PurchaseRequestLinesApi();

    /**
     * Create a Purchase Request Line
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createPurchaseRequestLineTest() throws ApiException {
        //PurchaseRequestLine purchaseRequestLine = null;
        //PurchaseRequestLine response = api.createPurchaseRequestLine(purchaseRequestLine);
        // TODO: test validations
    }

    /**
     * Delete a Purchase Request Line
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePurchaseRequestLineTest() throws ApiException {
        //Long id = null;
        //api.deletePurchaseRequestLine(id);
        // TODO: test validations
    }

    /**
     * Get an Purchase Request Line by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPurchaseRequestLineByIdTest() throws ApiException {
        //Long id = null;
        //String fields = null;
        //PurchaseRequestLine response = api.getPurchaseRequestLineById(id, fields);
        // TODO: test validations
    }

    /**
     * Test Purchase Request lines service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pingPurchaseRequestLineTest() throws ApiException {
        //String response = api.pingPurchaseRequestLine();
        // TODO: test validations
    }

    /**
     * Get a Purchase Request Lines collection
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryPurchaseRequestLineTest() throws ApiException {
        //String filter = null;
        //String sort = null;
        //Integer offset = null;
        //Integer limit = null;
        //String fields = null;
        //PurchaseRequestLineList response = api.queryPurchaseRequestLine(filter, sort, offset, limit, fields);
        // TODO: test validations
    }

    /**
     * Partial update of a Purchase Request Line
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePartialPurchaseRequestLineTest() throws ApiException {
        //Long id = null;
        //PurchaseRequestLine purchaseRequestLine = null;
        //api.updatePartialPurchaseRequestLine(id, purchaseRequestLine);
        // TODO: test validations
    }

    /**
     * Full update of a Purchase Request Line. If Purchase Request Line doesn&#39;t exist, it&#39;s created.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePurchaseRequestLineTest() throws ApiException {
        //Long id = null;
        //PurchaseRequestLine purchaseRequestLine = null;
        //api.updatePurchaseRequestLine(id, purchaseRequestLine);
        // TODO: test validations
    }

}
