/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.api;

import fr.everwin.sx.client.*;
import fr.everwin.sx.client.auth.*;
import fr.everwin.sx.client.model.ErrorMessage;
import fr.everwin.sx.client.model.SkillDomain;
import fr.everwin.sx.client.model.SkillDomainList;
import fr.everwin.sx.client.model.SkillLevelList;
import fr.everwin.sx.client.model.SkillList;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SkillDomainsApi
 */
public class SkillDomainsApiTest {

    private final SkillDomainsApi api = new SkillDomainsApi();

    /**
     * Create a skill domain
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        //SkillDomain skillDomain = null;
        //api.create(skillDomain);
        // TODO: test validations
    }

    /**
     * Delete a Skill Domain
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteTest() throws ApiException {
        //Long id = null;
        //api.delete(id);
        // TODO: test validations
    }

    /**
     * Get a Skill Domain by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        //Long id = null;
        //String fields = null;
        //SkillDomain response = api.getById(id, fields);
        // TODO: test validations
    }

    /**
     * Get a collection of skill levels for the given domain
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLevelsTest() throws ApiException {
        //Long id = null;
        //String fields = null;
        //SkillLevelList response = api.getLevels(id, fields);
        // TODO: test validations
    }

    /**
     * Get a collection of skills for the given domain
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSkillsTest() throws ApiException {
        //Long id = null;
        //String fields = null;
        //SkillList response = api.getSkills(id, fields);
        // TODO: test validations
    }

    /**
     * Test Skill Domains service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pingTest() throws ApiException {
        //String response = api.ping();
        // TODO: test validations
    }

    /**
     * Get a Skill Domain collection
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryTest() throws ApiException {
        //String filter = null;
        //String sort = null;
        //Integer offset = null;
        //Integer limit = null;
        //String fields = null;
        //SkillDomainList response = api.query(filter, sort, offset, limit, fields);
        // TODO: test validations
    }

    /**
     * Full update of a Skill Domain. If Skill Domain doesn&#39;t exist, it&#39;s created.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTest() throws ApiException {
        //Long id = null;
        //SkillDomain skillDomain = null;
        //api.update(id, skillDomain);
        // TODO: test validations
    }

    /**
     * Partial update of a Skill Domain
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePartialTest() throws ApiException {
        //Long id = null;
        //SkillDomain skillDomain = null;
        //api.updatePartial(id, skillDomain);
        // TODO: test validations
    }

}
