/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.02.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.api;

import fr.everwin.sx.client.ApiException;
import org.junit.jupiter.api.Test;

/**
 * API tests for SpancoStepsApi
 */
public class SpancoStepsApiTest {

    private final SpancoStepsApi api = new SpancoStepsApi();

    /**
     * Create a spanco step
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSpancoStepTest() throws ApiException {
        //SpancoStep spancoStep = null;
        //SpancoStep response = api.createSpancoStep(spancoStep);
        // TODO: test validations
    }

    /**
     * Delete a spanco step
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSpancoStepTest() throws ApiException {
        //Long id = null;
        //api.deleteSpancoStep(id);
        // TODO: test validations
    }

    /**
     * Get a spanco step by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSpancoStepByIdTest() throws ApiException {
        //Long id = null;
        //String fields = null;
        //SpancoStep response = api.getSpancoStepById(id, fields);
        // TODO: test validations
    }

    /**
     * Test spanco steps service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pingSpancoStepTest() throws ApiException {
        //String response = api.pingSpancoStep();
        // TODO: test validations
    }

    /**
     * Get a collection of spanco steps
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void querySpancoStepTest() throws ApiException {
        //String filter = null;
        //String sort = null;
        //Integer offset = null;
        //Integer limit = null;
        //String fields = null;
        //SpancoStepList response = api.querySpancoStep(filter, sort, offset, limit, fields);
        // TODO: test validations
    }

    /**
     * Partial update of a spanco step
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePartialSpancoStepTest() throws ApiException {
        //Long id = null;
        //SpancoStep spancoStep = null;
        //api.updatePartialSpancoStep(id, spancoStep);
        // TODO: test validations
    }

    /**
     * Full update of a spanco step. If spanco step doesn&#39;t exist, it&#39;s created.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSpancoStepTest() throws ApiException {
        //Long id = null;
        //SpancoStep spancoStep = null;
        //api.updateSpancoStep(id, spancoStep);
        // TODO: test validations
    }

}
