/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.api;

import fr.everwin.sx.client.*;
import fr.everwin.sx.client.auth.*;
import fr.everwin.sx.client.model.Document;
import fr.everwin.sx.client.model.DocumentList;
import fr.everwin.sx.client.model.ErrorMessage;
import fr.everwin.sx.client.model.FormDataContentDisposition;
import fr.everwin.sx.client.model.SupplierInvoice;
import fr.everwin.sx.client.model.SupplierInvoiceLine;
import fr.everwin.sx.client.model.SupplierInvoiceLineList;
import fr.everwin.sx.client.model.SupplierInvoiceList;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SupplierInvoicesApi
 */
public class SupplierInvoicesApiTest {

    private final SupplierInvoicesApi api = new SupplierInvoicesApi();

    /**
     * Create a Supplier Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        //SupplierInvoice supplierInvoice = null;
        //api.create(supplierInvoice);
        // TODO: test validations
    }

    /**
     * Create a new document for the supplier invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createDocumentTest() throws ApiException {
        //Long id = null;
        //Document document = null;
        //api.createDocument(id, document);
        // TODO: test validations
    }

    /**
     * Create a Supplier Invoice Line for A Supplier invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSupplierInvoiceLineTest() throws ApiException {
        //Long id = null;
        //SupplierInvoiceLine supplierInvoiceLine = null;
        //api.createSupplierInvoiceLine(id, supplierInvoiceLine);
        // TODO: test validations
    }

    /**
     * Delete a Supplier Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteTest() throws ApiException {
        //Long id = null;
        //api.delete(id);
        // TODO: test validations
    }

    /**
     * Delete a supplier invoice document
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteDocumentTest() throws ApiException {
        //Long id = null;
        //Long did = null;
        //api.deleteDocument(id, did);
        // TODO: test validations
    }

    /**
     * Delete a Supplier Invoice Line  for a Supplier invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteSupplierInvoiceLineTest() throws ApiException {
        //Long id = null;
        //Long lineid = null;
        //api.deleteSupplierInvoiceLine(id, lineid);
        // TODO: test validations
    }

    /**
     * Get physical file linked to the supplier invoice document
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void downloadDocumentTest() throws ApiException {
        //Long id = null;
        //Long did = null;
        //api.downloadDocument(id, did);
        // TODO: test validations
    }

    /**
     * Get an Supplier Invoice by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        //Long id = null;
        //String fields = null;
        //SupplierInvoice response = api.getById(id, fields);
        // TODO: test validations
    }

    /**
     * Get a supplier invoice document by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDocumentByIdTest() throws ApiException {
        //Long id = null;
        //Long did = null;
        //String fields = null;
        //Document response = api.getDocumentById(id, did, fields);
        // TODO: test validations
    }

    /**
     * Get a collection of documents for the given supplier invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDocumentsTest() throws ApiException {
        //Long id = null;
        //String filter = null;
        //String sort = null;
        //Integer offset = null;
        //Integer limit = null;
        //String fields = null;
        //DocumentList response = api.getDocuments(id, filter, sort, offset, limit, fields);
        // TODO: test validations
    }

    /**
     * Get a supplier invoice line for the given supplier invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSupplierInvoiceLineByIdTest() throws ApiException {
        //Long id = null;
        //Long lineid = null;
        //String fields = null;
        //SupplierInvoiceLine response = api.getSupplierInvoiceLineById(id, lineid, fields);
        // TODO: test validations
    }

    /**
     * Get a collection of supplier invoice lines for the given supplier invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSupplierInvoiceLinesTest() throws ApiException {
        //Long id = null;
        //String filter = null;
        //String sort = null;
        //Integer offset = null;
        //Integer limit = null;
        //String fields = null;
        //SupplierInvoiceLineList response = api.getSupplierInvoiceLines(id, filter, sort, offset, limit, fields);
        // TODO: test validations
    }

    /**
     * Test Supplier Invoices service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pingTest() throws ApiException {
        //String response = api.ping();
        // TODO: test validations
    }

    /**
     * Get a Supplier Invoices collection
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryTest() throws ApiException {
        //String filter = null;
        //String sort = null;
        //Integer offset = null;
        //Integer limit = null;
        //String fields = null;
        //SupplierInvoiceList response = api.query(filter, sort, offset, limit, fields);
        // TODO: test validations
    }

    /**
     * Full update of a Supplier Invoice. If Supplier Invoice doesn&#39;t exist, it&#39;s created.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTest() throws ApiException {
        //Long id = null;
        //SupplierInvoice supplierInvoice = null;
        //api.update(id, supplierInvoice);
        // TODO: test validations
    }

    /**
     * Full update of a supplier invoice document. If document doesn&#39;t exist, it&#39;s created.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateDocumentTest() throws ApiException {
        //Long id = null;
        //Long did = null;
        //Document document = null;
        //api.updateDocument(id, did, document);
        // TODO: test validations
    }

    /**
     * Partial update of a Supplier Invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePartialTest() throws ApiException {
        //Long id = null;
        //SupplierInvoice supplierInvoice = null;
        //api.updatePartial(id, supplierInvoice);
        // TODO: test validations
    }

    /**
     * Partial update of a document supplier invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePartialDocumentTest() throws ApiException {
        //Long id = null;
        //Long did = null;
        //Document document = null;
        //api.updatePartialDocument(id, did, document);
        // TODO: test validations
    }

    /**
     * Partial update of a Supplier Invoice Line  for a Supplier invoice
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePartialSupplierInvoiceLineTest() throws ApiException {
        //Long id = null;
        //Long lineid = null;
        //SupplierInvoiceLine supplierInvoiceLine = null;
        //api.updatePartialSupplierInvoiceLine(id, lineid, supplierInvoiceLine);
        // TODO: test validations
    }

    /**
     * Full update of a Supplier Invoice Line for a Supplier invoice. If Supplier Invoice Line doesn&#39;t exist, it&#39;s created.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSupplierInvoiceLineTest() throws ApiException {
        //Long id = null;
        //Long lineid = null;
        //SupplierInvoiceLine supplierInvoiceLine = null;
        //api.updateSupplierInvoiceLine(id, lineid, supplierInvoiceLine);
        // TODO: test validations
    }

    /**
     * Upload physical file linked to the supplier invoice document
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadDocumentTest() throws ApiException {
        //Long id = null;
        //Long did = null;
        //FormDataContentDisposition _file = null;
        //api.uploadDocument(id, did, _file);
        // TODO: test validations
    }

}
