/*
 * Everwin API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.01.00
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.everwin.sx.client.api;

import fr.everwin.sx.client.*;
import fr.everwin.sx.client.auth.*;
import fr.everwin.sx.client.model.ErrorMessage;
import fr.everwin.sx.client.model.SupplierReceivingNoteLine;
import fr.everwin.sx.client.model.SupplierReceivingNoteLineList;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SupplierReceivingNoteLinesApi
 */
public class SupplierReceivingNoteLinesApiTest {

    private final SupplierReceivingNoteLinesApi api = new SupplierReceivingNoteLinesApi();

    /**
     * Create a supplier receiving note Line
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        //SupplierReceivingNoteLine supplierReceivingNoteLine = null;
        //api.create(supplierReceivingNoteLine);
        // TODO: test validations
    }

    /**
     * Delete a supplier receiving note line
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteTest() throws ApiException {
        //Long id = null;
        //api.delete(id);
        // TODO: test validations
    }

    /**
     * Get an supplier receiving note Line by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        //Long id = null;
        //String fields = null;
        //SupplierReceivingNoteLine response = api.getById(id, fields);
        // TODO: test validations
    }

    /**
     * Test supplier receiving note lines service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pingTest() throws ApiException {
        //String response = api.ping();
        // TODO: test validations
    }

    /**
     * Get a supplier receiving note lines collection
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryTest() throws ApiException {
        //String filter = null;
        //String sort = null;
        //Integer offset = null;
        //Integer limit = null;
        //String fields = null;
        //SupplierReceivingNoteLineList response = api.query(filter, sort, offset, limit, fields);
        // TODO: test validations
    }

    /**
     * Full update of a supplier receiving note Line. If supplier receiving note Line doesn&#39;t exist, it&#39;s created.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTest() throws ApiException {
        //Long id = null;
        //SupplierReceivingNoteLine supplierReceivingNoteLine = null;
        //api.update(id, supplierReceivingNoteLine);
        // TODO: test validations
    }

    /**
     * Partial update of a supplier receiving note line
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePartialTest() throws ApiException {
        //Long id = null;
        //SupplierReceivingNoteLine supplierReceivingNoteLine = null;
        //api.updatePartial(id, supplierReceivingNoteLine);
        // TODO: test validations
    }

}
